cloudnativedaysjp/dreamkast-infra

manifests/app/dreamkast/base/kustomization.yaml
manifests/app/dreamkast/base/pdb.yaml

Nodeの停止が発生しても最低1台以上のPodが動くようにPodDisruptionBudgetを入れる

Add PodDisruptionBudget

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

関連PR: https://github.com/cloudnativedaysjp/dreamkast/pull/614

initContainerでdb:migrate等をやるようにした

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/hpa.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/hpa.yaml

https://github.com/cloudnativedaysjp/dreamkast/pull/617 この辺が prod に release されてからこの PR を merge する。

add HPA in production

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Scale up on prod

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/hpa.yaml

[production] add hpa in dreamkast-ui

---

manifests/app/dreamkast/overlays/staging/main/secret.yaml

Modify secret for stg

---

manifests/argocd/overlays/development/argocd-apps/prometheus.yaml
manifests/argocd/overlays/production/argocd-apps/prometheus.yaml
manifests/infra/contour/base/contour.yaml
manifests/infra/prometheus/base/kustomization.yaml
manifests/infra/prometheus/base/monitor.yaml
manifests/infra/prometheus/base/node-exporter.yaml
manifests/infra/prometheus/base/prometheus.yaml
manifests/infra/prometheus/overlays/development/kustomization.yaml
manifests/infra/prometheus/overlays/production/kustomization.yaml

ref #426 
#454 と #464 を整理しました。

add prometheus

---

manifests/argocd/overlays/development/argocd-apps/grafana-ingress.yaml
manifests/argocd/overlays/production/argocd-apps/grafana-ingress.yaml
manifests/infra/grafana-ingress/overlays/development/ingress.yaml
manifests/infra/grafana-ingress/overlays/production/ingress.yaml

Add grafana ingress

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/hpa.yaml

CODTでやった以下の対応と同じことをやった
https://github.com/cloudopsdays/dreamkast-infra/pull/213
https://github.com/cloudopsdays/dreamkast-infra/pull/214
https://github.com/cloudopsdays/dreamkast-infra/pull/215

Upgrade resource claim for production

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Shrink hpa after event

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/template/deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/template/kustomization.yaml

Pod が起動しない不具合を確認.
確認したところ環境変数が設定されておらず、mail-worker の deployment の設定に不足があったことが原因だと思われる.
template に mail-worker の deployment を追加した.
development 以下で deployment を修正して apply -> ステータスを確認.
https://github.com/cloudnativedaysjp/dreamkast/pull/716 をビルドしてそのイメージで  mail-worker が動作していることを確認.

mail-worker の起動しない不具合の修正

---

manifests/app/dreamkast/overlays/staging/main/secret.yaml

DB再作成に伴い新しく作ったSecretsに変更。
エンドポイントは変わりません

Modify staging credential

---

cfn/rds.yaml

スロークエリログをRDSのコントロールパネルから閲覧できるようにする

Add slow query param

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml

- stop: CICD2021
- start: CNDT2021
fix https://github.com/cloudnativedaysjp/dreamkast/issues/845

update notification of registration status

---

manifests/app/dreamkast/overlays/development/dk-846/deployment-dreamkast.yaml

DaemonSetsのContainer portじゃなくてService名で引くようにしたらうまくいった

Use service address

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml

https://github.com/cloudnativedaysjp/cndt2021/issues/41

add cron job to notify left idea issues

---

manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

AWS_REGION環境変数が無くてReview appでエラーが出ていたので追加

Add AWS_REGION env

---

cfn/eks-nodes.yaml

Due to updates https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#iam-policy

Update Autoscaler's IAM Policy

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml

* dreamkast に ActiveJob 用の環境変数を追加
* mail-worker の manifest を作成
* kustomization に mail-worker を追加

productionでSQSが使えるように環境変数を追加

---

manifests/infra/contour/base/contour.yaml
manifests/infra/contour/overlays/development/contour.yaml
manifests/infra/contour/overlays/development/kustomization.yaml

ContourのメトリクスがGrafanaで取れてない現状があるので最新にしてみる。
変更内容的にはCRD周りとEnvoyとかそのへんのバージョンアップが主

Upgrade contour

---

manifests/argocd/base/kustomization.yaml
manifests/argocd/overlays/dev-with-secrets/kustomization.yaml
manifests/argocd/overlays/prd-with-secrets/kustomization.yaml
manifests/deploy.sh

ArgoCD Application の annotations に argocd-image-updater 用の設定をするのは別途 PR を出します

add ArgoCD Image Updater

---

manifests/infra/reviewapp-operator/base/kustomization.yaml
manifests/reviewapps/dreamkast.yaml

* ref. https://github.com/cloudnativedaysjp/reviewapp-operator/issues/53

Fix reviewapp

---

manifests/argocd/overlays/prd/pods.yaml

Mitigate https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1074

Increase CPU limits on Argo repo server

---

manifests/argocd/overlays/dev/pods.yaml
manifests/argocd/overlays/prd/pods.yaml

まだ足りなかったのとDevでもサチってた
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1075

update resource claim again

---

manifests/argocd-apps/prd/grafana.yaml

closes #1056
closes #1089 
closes #1090 
ref #1055 #426

prd: grafana as statefulset and add manually managed dashboards

---

cfn/eks-nodes.yaml

attach AWSElementalMediaLiveFullAccess to Node

---

manifests/app/dreamkast/overlays/development/dk-991/viewer-counter.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/production/main/viewer-count.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/viewer-count.yaml
manifests/app/dreamkast/overlays/template/kustomization.yaml
manifests/app/dreamkast/overlays/template/viewer-count.yaml
manifests/reviewapps/dreamkast.yaml

Add viewer-counter cronjob

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1136
本番前にスケールする用

Update prd hpa

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

https://github.com/cloudnativedaysjp/dreamkast/pull/993

Add namespace field for jeager

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

忘れないうちにPR出しておきます。もとのmin: 4 max: 10でいいですかね？

prd: reduce the number of HPA replicas

---

manifests/infra/contour/base/contour.yaml

本番のContourを上げるやつ
下記を含む
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/748
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1130

Update Contour on prd

---

manifests/argocd-apps/dev/cert-manager.yaml

dev: bump cert-manager from v1.5.3 to v1.6.1

---

manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml
manifests/reviewapps/dreamkast.yaml

テンプレートとdreamkast appsで設定したいenvの値を間違えてinit dbの方に入れてた

Fix namespace env

---

manifests/argocd-apps/dev/jaeger.yaml

OperatorじゃなくてHelmで個別にいれた
https://github.com/jaegertracing/helm-charts
アプリ側は https://github.com/cloudnativedaysjp/dreamkast/pull/993 だけど先にこれをいれる

Add Jaeger

---

manifests/argocd-apps/dev/grafana.yaml

This reverts commit 13832261de14d6555e5aecb8fb2ac315da56492a.

Revert "Add jaeger datasource to grafana"

---

manifests/argocd-apps/dev/jaeger.yaml

Fix chart name

---

manifests/argocd-apps/prd/grafana.yaml
manifests/argocd-apps/prd/jaeger.yaml

Add jaeger on prd

---

manifests/infra/prometheus/overlays/development/kustomization.yaml
manifests/infra/prometheus/overlays/development/service-selector.yaml

dev: Remove prometheus app selector

---

manifests/argocd-apps/dev/external-secrets.yaml

Dev changes due to https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1238

dev: Modify API calls frequency on external secrets

---

manifests/app/dreamkast/base/deployment.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

#1208 のレビューを文章で書きましたが伝わりにくいと思ったので、実際に PR を出しました。
* manifests/app/dreamkast/overlays/template ではなく、manifests/reviewapps 以下に dev マニフェストの更新内容を反映した
* dev 以外の環境に影響が出ないよう、manifests/app/dreamkast/base/deployment.yaml を編集しないようにした
* 代わりに manifests/reviewapps 以下の kustomize にてゴチャゴチャやるようにした

review of #1208

---

manifests/argocd-apps/dev/external-secrets.yaml

内部処理でタイムアウトする時間をbotのpolling時間よりも長くした

modify timeout

---

manifests/argocd-apps/dev/external-secrets.yaml

add comment

---

manifests/argocd-apps/dev/argocd-ingress.yaml
manifests/argocd-apps/dev/argocd.yaml
manifests/argocd-apps/dev/cert-manager.yaml
manifests/argocd-apps/dev/contour.yaml
manifests/argocd-apps/dev/dreamkast.yaml
manifests/argocd-apps/dev/external-secrets.yaml
manifests/argocd-apps/dev/grafana-ingress.yaml
manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/dev/jaeger.yaml
manifests/argocd-apps/dev/loki.yaml
manifests/argocd-apps/dev/metrics-server.yaml
manifests/argocd-apps/dev/prometheus.yaml
manifests/argocd-apps/dev/reviewapp-operator.yaml
manifests/argocd/base/kustomization.yaml
manifests/argocd/base/projects.yaml

ArgoCDのプロジェクトをインフラ、アプリ、監視の観点で分けるようにした
ReviewApps Operatorについてはこれでよいか要検討である

dev: refacor argo project

---

manifests/app/argocd-apps/development/dreamkast-api-mock.yaml
manifests/app/argocd-apps/development/dreamkast-dk-1018.yaml
manifests/app/argocd-apps/development/dreamkast-dk-1035.yaml
manifests/app/argocd-apps/development/dreamkast-staging.yaml
manifests/application-dev.yaml
manifests/argocd-apps/dev/aws-ebs-csi-driver.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

Stagingクラスターの中にあるリソースでProjectsの変更漏れがあったので変更した

modify all projects in dev/stg

---

manifests/app/argocd-apps/production/dreamkast-main.yaml
manifests/app/argocd-apps/production/dreamkast-maintenance.yaml
manifests/app/argocd-apps/production/dreamkast-releasebot.yaml
manifests/application-prd.yaml
manifests/argocd-apps/prd/argocd-ingress.yaml
manifests/argocd-apps/prd/argocd-notifications.yaml
manifests/argocd-apps/prd/argocd.yaml
manifests/argocd-apps/prd/cert-manager.yaml
manifests/argocd-apps/prd/contour.yaml
manifests/argocd-apps/prd/dreamkast.yaml
manifests/argocd-apps/prd/external-secrets.yaml
manifests/argocd-apps/prd/grafana.yaml
manifests/argocd-apps/prd/jaeger.yaml
manifests/argocd-apps/prd/loki.yaml
manifests/argocd-apps/prd/metrics-server.yaml
manifests/argocd-apps/prd/prometheus.yaml
manifests/argocd/overlays/production/argocd-apps/dreamkast.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1256 と https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1266 を本番にも適用

prd: modify prd argo projects

---

manifests/argocd-apps/prd/aws-ebs-csi-driver.yaml

prd: manage aws-ebs-csi-driver by argocd

---

manifests/argocd-apps/prd/aws-ebs-csi-driver.yaml

prd: aws-ebs-csi-driver to infra project

---

manifests/argocd-apps/prd/external-secrets.yaml

prd changes due to https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1238
Shall be merged after https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1239

prd: modify API calls frequency on external secrets

---

manifests/argocd-apps/prd/grafana.yaml

Grafana in development environment will be updated to fix CVE-2021-43798, path traversal.
https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
ref #1277

prd: bump grafana from 8.2.3 to 8.3.1 to fix CVE-2021-43798

---

manifests/argocd-apps/prd/cert-manager.yaml

close #1198
#1199 でdevに適用して動作確認してから。

prd: bump cert-manager from v1.5.3 to v1.6.1

---

cfn/sqs.yaml

Fix sqs resource

---

manifests/argocd-apps/dev/grafana.yaml

This PR adds [The Kubernetes Persistent Volumes](https://grafana.com/grafana/dashboards/13646) dashboard to our Grafana environment.
Related to https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1265

Add PV Usage Dashboard

---

manifests/argocd-apps/prd/grafana.yaml

Apply https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1294 to production

Add PV Usage Dashboard on Production

---

manifests/infra/prometheus/overlays/production/prometheus.yaml

Add retention param
Fixes #1265

Add retention param 

---

manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/prd/grafana.yaml

O11y2022 members want to login to grafana as admin.

Fix allowed group

---

manifests/infra/prometheus/base/monitor.yaml
manifests/infra/prometheus/overlays/development/service-monitor.yaml
manifests/infra/telegraf/base/kustomization.yaml
manifests/infra/telegraf/base/service.yaml

Add prometheus telegraf monitor

Add prometheus telegraf monitor

---

manifests/infra/telegraf/base/service.yaml

Add label to telegraf service

---

manifests/argocd-apps/prd/telegraf.yaml
manifests/infra/prometheus/base/monitor.yaml
manifests/infra/prometheus/overlays/development/service-monitor.yaml
manifests/infra/telegraf/base/service.yaml
manifests/infra/telegraf/overlays/production/deployment.yaml
manifests/infra/telegraf/overlays/production/kustomization.yaml
manifests/infra/telegraf/overlays/production/secrets.yaml

Add telegraf to prod
#1280 and #1302

Add telegraf to prod

---

manifests/infra/telegraf/overlays/production/deployment.yaml

Fix quotation

---

manifests/argocd-apps/dev/grafana.yaml

ref: #1277
This update doesn't include breaking changes.

dev: Bump grafana helm chart from 6.15.0 to 6.19.2, grafana image from 8.3.1 to 8.3.3

---

manifests/infra/telegraf/base/configmap.yaml

fixed a typo

---

manifests/infra/telegraf/base/configmap.yaml

「メトリクスごとにSQLを実行する」から「ごそっととってPromQLで集計する」方針にする。
?

remove inputs.sql.query that fetch particular column

---

manifests/infra/telegraf/base/configmap.yaml

Fix cloudnativedaysjp/observability#13
1. Remove talk category as it is unused
2. Add proposed_items assumed_visitor and execution_phase
Executed new updated SQL manually

Fix observability 13.

---

manifests/reviewapps/dreamkast.yaml

Run the task only on the review_app environment to create the SQS queue

Change init container to create SQS

---

manifests/reviewapps/dreamkast.yaml

fix container name by snake case

Fix invalid container name

---

manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml

#1321 for staging environments.
If this is confirmed to work without problems, apply it to the production environment.
not yet

modify staging worker command

---

manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml

fix staging manifests

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/delete-deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/delete-deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

This PR is refactoring.
In below PRs, install `fifo-worker` & remove `mail-worker` to overlay manifests.
* #1208
* #1287
* #1289
In this PR, reflect to base manifests on above changes.
* in BASE branch (70bbc035)
```bash
kustomize build manifests/app/dreamkast/overlays/production/main > /tmp/production.yaml
kustomize build manifests/app/dreamkast/overlays/staging/main > /tmp/staging.yaml
```
* in HEAD branch (0fdbed30)
* confirmed no outputs
```bash
diff <(kustomize build manifests/app/dreamkast/overlays/production/main) /tmp/production.yaml
diff <(kustomize build manifests/app/dreamkast/overlays/staging/main) /tmp/staging.yaml
```

delete descriptions related of dreamkast-mail-worker

---

manifests/argocd-apps/dev/grafana.yaml

Synthetics Canaryを止めたため、不要になった。
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1640580393051400
Fixes # N/A
🤔

dev: remove AWS CloudWatch Synthetics dashboard from grafana

---

manifests/argocd-apps/prd/grafana.yaml

Synthetics Canaryを止めたため、不要になった。devは #1339
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1640580393051400
Fixes # N/A
🤔

prd: remove AWS CloudWatch Synthetics dashboard from grafana

---

manifests/argocd-apps/prd/grafana.yaml

Fixes #1277 (issue)
ref:
- https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1293

prd: Bump grafana helm chart from 6.15.0 to 6.19.2, grafana image from 8.3.1 to 8.3.3

---

manifests/argocd-apps/dev/jaeger.yaml
manifests/argocd-apps/prd/jaeger.yaml

Minimize Jaeger Elasticsearch instance to reduce infra cost

Reduce elasticsearch

---

manifests/argocd-apps/dev/grafana.yaml

Add AWS Billing Dashboard
1. `git switch feat/kono/billing_dashboard`
2. `kubectl apply -f manifests/argocd-apps/dev/grafana.yaml`
3.  access: https://grafana.dev.cloudnativedays.jp/d/AWSBillig/aws-billing

Add AWS Billing Dashboard

---

dashboards/o11y2022-cfp.json
manifests/argocd-apps/dev/grafana.yaml

ref https://github.com/cloudnativedaysjp/observability/issues/19
ref #1082
1. I edited this line to `grafana-okepy`.
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/528085fee347b5a94143307b1dc5369c98cb8955/manifests/argocd-apps/dev/grafana.yaml#L5
1. `kubectl apply -f manifests/argocd-apps/dev/grafana.yaml`
2. `kubectl port-forward svc/grafana-okepy 8000:80`
3. access `http://localhost:8080`
- user: `kubectl get secret grafana-okepy -ojsonpath='{.data.admin-user}' | base64 -d | pbcopy`
- password: `kubectl get secret grafana-okepy -ojsonpath='{.data.admin-password}' | base64 -d | pbcopy`

dev: add #o11y2022 proposal dashboard

---

manifests/app/dreamkast/overlays/production/main/kustomization.yaml

Followup of https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1361
ファイルを消したけどkustomizationのほうで変えるのを忘れてた

Remove redis.yaml from kustomization

---

manifests/argocd-apps/dev/social-analysis.yaml
manifests/infra/prometheus/overlays/development/service-monitor.yaml
manifests/infra/social-analysis/base/deployment.yaml
manifests/infra/social-analysis/base/kustomization.yaml
manifests/infra/social-analysis/base/service.yaml
manifests/infra/social-analysis/overlays/development/kustomization.yaml
manifests/infra/social-analysis/overlays/development/secrets.yaml

Deploy custom social analysis exporter.
Image build based on https://github.com/cloudnativedaysjp/social-analysis
Fix 
- cloudnativedaysjp/observability#15 
- cloudnativedaysjp/observability#29
- cloudnativedaysjp/observability#31 
- cloudnativedaysjp/observability#37
Tested on local kubernetes and verified new exporter will show the following results.
```
social_twitter_favorites{queryString="#o11y2022",screenName="cloudnativedays",tweetId="1479287673282048000",} 7.0
social_twitter_favorites{queryString="#o11y2022",screenName="cloudnativedays",tweetId="1477776728152240129",} 5.0
social_twitter_favorites{queryString="#o11y2022",screenName="cloudnativedays",tweetId="1479377275846291458",} 3.0
social_twitter_favorites{queryString="#o11y2022",screenName="cloudnativedays",tweetId="147929595506 …
```

Deploy custom social analysis exporter（Test環境）

---

manifests/infra/reviewapp-operator/base/kustomization.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

update setting of reviewapp-operator
* bump up version: v0.0.3 > v0.0.7
* specify `ignoreLabels` &  `ignoreTitleExp` fields in `dreamkast{,-ui}` manifests (for ReviewApps).

update setting of reviewapp-operator

---

manifests/argocd-apps/dev/jaeger.yaml

Elasticsearchがシングルノードで動いていないのでそれを治す
ref. https://github.com/elastic/helm-charts/issues/312#issuecomment-783804066

Make single node es work

---

manifests/infra/telegraf/overlays/development/configmap.yaml
manifests/infra/telegraf/overlays/development/kustomization.yaml

Fixes 
cloudnativedaysjp/observability#39

Dev test for cloudnativedaysjp/observability#39

---

manifests/argocd-apps/dev/jaeger.yaml

Cassandraが勝手にデプロイされる・・・！フォーマットの問題臭いので治す

modify format

---

manifests/infra/mysql-o11y/overlays/development/kustomization.yaml
manifests/infra/mysql-o11y/overlays/production/kustomization.yaml

✅ Closes: https://github.com/cloudnativedaysjp/observability/issues/40

fix: 🐛 typo in kustomization.yaml secrets.yaml -> secret.yaml

---

manifests/infra/mysql-o11y/base/deployment.yaml

fix: 🐛 couldn't find key user in Secret

---

manifests/infra/mysql-o11y/base/cronjob.yaml

Deploymentsで指定してるsecretとCronJobで指定してるsecretのキーが違って起動してもConfigErrorでエラーになっていた

Fix secret key ref

---

terraform/uptime_robot/.terraform.lock.hcl
terraform/uptime_robot/alerts.tf
terraform/uptime_robot/main.tf
terraform/uptime_robot/monitors.tf
terraform/uptime_robot/variables.tf

Uptime robot

---

terraform/uptime_robot/main.tf

modified main.tf to add provider

---

terraform/uptime_robot/.terraform.lock.hcl
terraform/uptime_robot/main.tf

added backent to main.tf

---

terraform/uptime_robot/monitors.tf

added ignore_changes to monitors.tf

---

cfn/eks-nodes-bottlerocket.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1368 で変数展開するようにしたけど `!Sub` が必要でした… 後、AddTagsToResourceも必要だった。
ChangeSetをブランチで作って適用できることを確認済み。

変数展開のために!Subが必要だったのとタグをセットする権限も必要だった

---

manifests/infra/mysql-o11y/base/cronjob.yaml

Fix argument to work properly

---

manifests/infra/telegraf/overlays/development/deployment.yaml
manifests/infra/telegraf/overlays/development/secrets.yaml

Update DB to local replica (DevEnv)

---

manifests/infra/mysql-o11y/base/cronjob.yaml

- -p password → -ppassword 
- 左では、パスワードをシェルで指定することはできなかった。
- `--no-tablespaces`を追加
- https://qiita.com/katzueno/items/29d812eb3aafdb23b0bb

Update cronjob cmd

---

manifests/infra/mysql-o11y/base/cronjob.yaml

`/bin/sh`がなさそうだったので、`/bin/bash`を採用してみる

MySQL image don't have sh but have bash

---

manifests/infra/mysql-o11y/base/cronjob.yaml

環境変数の問題かなと思い、デバッグのために、echoしたいです。

デバッグ用のecho

---

manifests/infra/mysql-o11y/base/cronjob.yaml

fix escape

---

manifests/argocd-apps/dev/cert-manager.yaml

Update cert-manager to 1.7.1
https://github.com/cert-manager/cert-manager/releases/tag/v1.7.0 を見る限り、IngressClassの指定方法が昔のやりかた(アノテーション)じゃない限りは問題無さそう

update cert manager to 1.7.1

---

manifests/argocd-apps/dev/mysql-o11y.yaml

現在 Argocd Appsで指定しているnamespaceが間違っている。
なぜ、これによっておかしくなっているかは微妙ですが、唯一 `patchesStrategicMerge` に指定している `cronjobs` が元のをみつけられない？ことによるエラーではないかと推測中。

Fix namespace

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1425

Revert "Add Image"

---

cfn/eks-nodes-bottlerocket.yaml
cfn/eks.yaml
cfn/vpc.yaml

This brings some config changes on EKS to introduce Karpenter beforehand

Prepare config for introducing karpenter

---

manifests/argocd-apps/prd/external-secrets.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1431 for production

Add IRSA on Kubernetes External Secrets in production

---

.github/PULL_REQUEST_TEMPLATE.md

add pr template option

---

manifests/argocd-apps/prd/cluster-autoscaler.yaml

- Update AWS Cluster Autoscaler version
- Apply Cluster Autoscaler ArgoCD resource in production

update cluster autoscaler

---

cfn/eks-nodes-bottlerocket.yaml

IRSAに移行できた分のポリシーを剥がす
Apply after https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1432

Delete unnecessary policies on nodegroup

---

manifests/infra/contour/overlays/development/kustomization.yaml

Update contour on dev

---

manifests/argocd/base/kustomization.yaml

Fixes https://github.com/kubernetes-sigs/kustomize/issues/4261#issuecomment-955672673

Update Argo CD to 2.2

---

manifests/app/dreamkast/overlays/staging/main/secret.yaml
manifests/argocd-apps/dev/grafana-secret.yaml
manifests/infra/mysql-o11y/overlays/development/secret.yaml
manifests/infra/social-analysis/overlays/development/secrets.yaml
manifests/infra/telegraf/overlays/development/secrets.yaml
manifests/reviewapps/dreamkast.yaml
manifests/reviewapps/secret.yaml

Add Role Arn on External Secrets

---

manifests/app/dreamkast/overlays/staging/main/secret.yaml
manifests/argocd-apps/dev/external-secrets.yaml
manifests/argocd-apps/dev/grafana-secret.yaml
manifests/argocd-apps/prd/external-secrets.yaml
manifests/infra/mysql-o11y/overlays/development/secret.yaml
manifests/infra/social-analysis/overlays/development/secrets.yaml
manifests/infra/telegraf/overlays/development/secrets.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml
manifests/reviewapps/secret.yaml

Revert Kubernetes External Secrets

---

manifests/infra/prometheus/base/monitor.yaml
manifests/infra/prometheus/overlays/development/service-monitor.yaml

Twitter ExporterをPrometheus側で検知するために
`kustomize build ./` して問題ないことを確認しています。

Move prometheus service monitor to base

---

manifests/argocd-apps/prd/aws-cluster-autoscaler.yaml
manifests/argocd-apps/prd/aws-load-balancer-controller.yaml

Fixes https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1213 and https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1243 in production

Import AWS related controllers to Argo in production

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml
manifests/infra/mysql-o11y/overlays/production/cronjob.yaml

Remove duplicate RDS_HOST

---

manifests/argocd-apps/prd/mysql-o11y.yaml
manifests/infra/mysql-o11y/overlays/production/cronjob.yaml

Fixes cloudnativedaysjp/observability#44
MySQLの本番側の実装
Argocd.Devによると想定通り、午前２時にCronが流れている。
https://argocd.dev.cloudnativedays.jp/applications/mysql-o11y?resource=&node=%2FPod%2Fmonitoring%2Fmysql-o11y-27405690-22mlb

Move mysql prod

---

manifests/argocd-apps/dev/grafana.yaml

ref #1279 #1332
argocd.devでAuto Syncを無効にしてapplyしました。

[dev] grafana dashboardをprivate/publicに分類する

---

dashboards/o11y2022-cfp.json
manifests/argocd-apps/dev/grafana.yaml

`now`まで表示してもプロポーザル数に変化はないため、表示期間を狭める。

proposal dashboardの表示期間をプロポーザル受付期間に狭める

---

manifests/argocd-apps/dev/grafana.yaml

[dev] privateに残っていたo11y2022 proposalを削除する

---

manifests/infra/social-analysis/base/deployment.yaml

プレイベントハッシュタグ追加

---

manifests/argocd-apps/prd/grafana.yaml

prdのみUIからインストールしていたっぽいので、コード管理に移行する。

[prd] AWS Billing dashboardを追加する

---

manifests/infra/prometheus/overlays/development/service-monitor.yaml

Add dreamkast scraping config (dev only)

Add dreamkast scraping config (dev only)

---

dashboards/o11y2022-main.json
manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/prd/grafana.yaml

devのgrafanaで手動で作成したダッシュボードをdev, prodそれぞれに反映する

dashboardをdevのgrafanaの状態に合わせて更新

---

manifests/app/dreamkast/base/service.yaml

PrometheusのServiceMatchをするために必要なラベルの追加

add service label

---

manifests/app/dreamkast/base/service.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1500

Revert "add service label"

---

manifests/app/dreamkast/base/service.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1503

Revert "Revert "add service label""

---

manifests/infra/prometheus/overlays/development/probe.yaml

前の設定だとmetrics_pathが`/probe`になってしまう。
どうもこれが正しい設定の模様。

fix prober

---

manifests/infra/prometheus/overlays/development/probe.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1506

Revert "fix prober"

---

manifests/infra/prometheus/base/monitor.yaml

From @iaoiui 
```
プレイベントでデモする際に、プレイベント中にいいねしてもらって、そのtwitterのメトリクスを見せたいというユースケースを想定しています
プレイベントの前半20分の掴みでここを見せたいと思い、現状のinterval15分よりもう少し短い単位(1~5分)にすることで徐々に上がってる部分を見せたいという意図でした
```

Change interval to 3min

---

dashboards/o11y2022-main.json

[#1144 ](https://github.com/cloudnativedaysjp/dreamkast/pull/1144)で生成する、o11y2022の登録者数のメトリクスを表示するためのパネルを作成

o11y2022の登録者数用パネルを作成

---

manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml

run polling-harvest-job-and-update-video cronjob on production and staging

---

terraform/uptime_robot/monitors.tf

Modify tf file to monitor grafana from uptimerobot.

Update monitors.tf to monitor grafana from uptimerobot

---

manifests/infra/contour/base/kustomization.yaml
manifests/infra/contour/overlays/development/kustomization.yaml

Update Contour in production

---

manifests/argocd-apps/dev/aws-ebs-csi-driver.yaml

Update CSI in dev

---

manifests/argocd-apps/dev/jaeger.yaml

Upgrade Jaeger in dev

---

manifests/argocd-apps/dev/aws-load-balancer-controller.yaml

Upgrade LB Controller in dev

---

manifests/infra/contour/overlays/development/kustomization.yaml

Update Contour to fix its dependencies' vulnerabilities.
- github.com/prometheus/client_golang
- CVE-2022-21698 (7.5 High)
- Envoy https://groups.google.com/g/envoy-announce/c/bIUgEDKHl4g
- CVE-2022-21654 (7.3 High)
- CVE-2022-21655 (7.5 High)
- and 6 more

Update Contour to v1.20.1 in dev

---

manifests/argocd-apps/prd/aws-load-balancer-controller.yaml

Fixes https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1533 on production

Update LB Controller on production

---

manifests/argocd-apps/prd/jaeger.yaml

Fixes https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1534 on production

Update Jaeger on production

---

manifests/infra/contour/base/kustomization.yaml
manifests/infra/contour/overlays/development/kustomization.yaml

Fixes https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1545 for production

Address CVE on contour

---

manifests/argocd-apps/dev/aws-ebs-csi-driver.yaml
manifests/argocd-apps/prd/aws-ebs-csi-driver.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1532 for production
The following change is also contained due to a CVE
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/compare/helm-chart-aws-ebs-csi-driver-2.6.2...helm-chart-aws-ebs-csi-driver-2.6.3

Update csi prd

---

manifests/argocd-apps/prd/cert-manager.yaml

Update cert-manager on production

---

terraform/nextcloud/instance.tf

Fixes (https://github.com/cloudnativedaysjp/dreamkast-broadcast/issues/105)

Add backup disk for nextcloud

---

manifests/argocd-apps/dev/grafana.yaml

https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1536#issuecomment-1052915992 できれいになった。
この状態でフォルダー移動をするとどうなるか見てみたい。

dev: o11y2022 main ダッシュボードをpublicフォルダーに移す

---

manifests/argocd-apps/prd/grafana.yaml

視聴者数と、累積チャット数のダッシュボードを本番側Grafanaに反映
Fixes #1526

本番側ダッシュボードの更新

---

manifests/infra/prometheus-ingress/overlays/development/ingress.yaml
manifests/infra/prometheus-ingress/overlays/production/ingress.yaml

Add: Add remote write endpoint

---

manifests/infra/contour/base/auth-server.yaml
manifests/infra/prometheus-ingress/base/extension-service.yaml
manifests/infra/prometheus-ingress/overlays/development/ingress.yaml
manifests/infra/prometheus-ingress/overlays/development/secret.yaml
manifests/infra/prometheus-ingress/overlays/production/ingress.yaml
manifests/infra/prometheus-ingress/overlays/production/secret.yaml

Change: Change namespace "projectcontour"

---

terraform/uptime_robot/monitors.tf
terraform/uptime_robot/status.tf
terraform/uptime_robot/variables.tf

Add prometheus monitor

---

manifests/infra/prometheus/base/prometheus.yaml

Fixes https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1646489926065459?thread_ts=1646472545.459179&cid=C02MAP9EHAA
To enable remote write, we need to add 'remote-write-receiver' feature flag in a prometheus.
see https://prometheus.io/docs/prometheus/latest/feature_flags/#remote-write-receiver

Enable remote-write-receiver feature

---

manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/prd/grafana.yaml

Jaegerのクエリエンドポイントで指定してるポートがおかしいので治す

Fix Jaeger datasource endpoint port

---

manifests/argocd-apps/prd/grafana.yaml

本番Grafanaダッシュボードへの参加者登録数、チャット数、視聴者数の最新値ダッシュボードの追加
Fixes: https://github.com/cloudnativedaysjp/observability/issues/17

[prd]参加者登録数、チャット数、視聴者数の最新値ダッシュボードの追加

---

cfn/ecr-lifecycle-policy.yaml

Fixes #1334
This change add policies to ECR to decrease the fee.
This template has already applied and it's working well.
The name of stack is ECR-Lifecycle-Policy-dreamkast-ecs.

added CFn template #1334

---

manifests/infra/prometheus/base/prometheus.yaml
manifests/infra/prometheus/overlays/development/alert-rules.yaml
manifests/infra/prometheus/overlays/development/alertmanager.yaml
manifests/infra/prometheus/overlays/development/kustomization.yaml

Moved from
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1567

Monitor the monitor

---

manifests/infra/prometheus/overlays/development/alertmanager.yaml

下のIssueと同じミスをしていたっぽいです
https://github.com/prometheus-operator/prometheus-operator/issues/4006#issuecomment-846059307
一応↓のリンクでも確認しました
https://doc.crds.dev/github.com/prometheus-operator/prometheus-operator/monitoring.coreos.com/AlertmanagerConfig/v1alpha1@v0.54.0

alertmanager.yaml修正

---

manifests/argocd-apps/prd/grafana.yaml

開発環境に取り込んだ下記PRを本番にも取り込む
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1587

[Grafana]ダッシュボードの更新

---

manifests/argocd-apps/prd/grafana.yaml

文言修正したダッシュボードを本番Grafanaにもデプロイ
Related to https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1598

typoを修正したダッシュボードをデプロイ

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Increase HPA for production

---

dashboards/o11y2022-main.json
manifests/argocd-apps/prd/grafana.yaml

ダッシュボード表示がおかしいので直した
- [x I have checked backward/forward compatibility that may cause regarding this change.

Fix dashboard

---

dashboards/o11y2022-main.json
manifests/argocd-apps/prd/grafana.yaml

public dashboard の legend format を更新

Setting legend

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

本番終わったのでPod減らす

---

manifests/argocd/base/kustomization.yaml

Update Argo CD to 2.3

---

manifests/infra/prometheus/overlays/development/kube-state-metrics/alert-rules.yaml
manifests/infra/prometheus/overlays/development/kube-state-metrics/kustomization.yaml
manifests/infra/prometheus/overlays/development/kube-state-metrics/patch.yaml
manifests/infra/prometheus/overlays/development/kube-state-metrics/servicemonitor.yaml
manifests/infra/prometheus/overlays/development/kustomization.yaml

add kube-state-metrics & add ServiceMonitor for reviewapp-operator
- In my home environment (sorry, I cannot to show evidence🙏)

add kube-state-metrics & add ServiceMonitor for reviewapp-operator

---

manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/prd/grafana.yaml

Add grafana pichart panel

---

manifests/argocd-apps/dev/grafana.yaml

upgrade grafana

---

manifests/argocd-apps/dev/grafana.yaml

パスワード入力画面を消してSSOだけでログインするように見せる変更

disable login form

---

cfn/eks-nodes-bottlerocket.yaml

下のissueと同じ
https://github.com/cloudopsdays/dreamkast-infra_codt2022/issues/5

secrets manager read onlyのpolicyを追加

---

manifests/app/dreamkast-releasebot/base/deployment.yaml

no issue.
* dreamkast-releasebot: 
* add targets of CODT2022 repos
* https://github.com/cloudopsdays/dreamkast_codt2022
* https://github.com/cloudopsdays/dreamkast-ui_codt2022
* note: releasebot use https://github.com/showks-containerdaysjp account.
* required to add authority of pushing PR to https://github.com/cloudopsdays

dreamkast-releasebot: add targets (CODT2022 repos)

---

manifests/infra/prometheus/overlays/development/kube-state-metrics/alert-rules.yaml

no issues.
enable alert for reviewapp-operator.

enable alert for reviewapp-operator

---

manifests/argocd-apps/dev/loki.yaml

Update Loki for dev

---

manifests/argocd-apps/dev/loki.yaml

fix version

---

manifests/argocd-apps/dev/dreamkast.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/deployment-dreamkast.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/deployment-fifo-worker.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/ingress.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/polling-harvest-job-and-update-video.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/viewer-count.yaml
manifests/reviewapps/dreamkast-ui_codt2022/reviewappmanager.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/deployment-dreamkast.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/deployment-fifo-worker.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/ingress.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/polling-harvest-job-and-update-video.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/viewer-count.yaml
manifests/reviewapps/dreamkast_codt2022/reviewappmanager.yaml

None issue.
update for Review Apps of CODT2022

make ECR repo publish

---

manifests/argocd/base/kustomization.yaml

[](https://github.com/argoproj/argo-cd/releases/tag/v2.3.4)

ArgoCD security update

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

https://github.com/cloudnativedaysjp/dreamkast/issues/1233
As workaround, we need to reduce a number of pods.

ProdのPodを1にする

---

manifests/app/dreamkast/overlays/development/template-dk/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml
manifests/reviewapps/dreamkast-ui_codt2022/.mt-stable/ingress.yaml
manifests/reviewapps/dreamkast_codt2022/.mt-stable/ingress.yaml

Add routing rule for /_next endpoint for ui.
Fix https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1653222493590109

Add path /_next

---

dashboards/cnsec2022-cfp.json
manifests/argocd-apps/dev/grafana.yaml

ref: [cloudnativedaysjp/observability#53](https://github.com/cloudnativedaysjp/observability/issues/53)

dev: Add #cnsec2022 proposals dashboard

---

manifests/argocd-apps/prd/loki.yaml

Update Production loki

---

terraform/broadcast-switcher/instances.tf

add nginx02

---

terraform/broadcast-switcher/instances.tf

add nginx03

---

manifests/infra/telegraf/base/deployment.yaml

Fixes # [(issue)](https://github.com/cloudnativedaysjp/observability/issues/53#issuecomment-1142174424)

Update deployment.yaml to new conf_id

---

dashboards/cnsec2022-cfp.json

- CFPのメトリクスを表示するダッシュボードでCNSec2022に対応したIDに変更されていなかったため修正

dev: Change the ID of the metrics to be acquired

---

manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

Workaround https://github.com/cloudnativedaysjp/dreamkast/pull/1238
I already verified this configuration is working at dk-1242.
https://github.com/cloudnativedaysjp/dreamkast-infra/commit/80aa3584c0e58ee19c4953af827e62b7baa4698c

Add loadBalancerPolicy to enable sticky session

---

manifests/argocd-apps/dev/grafana.yaml

Update grafana security

---

manifests/argocd-apps/dev/grafana.yaml
manifests/argocd-apps/dev/jaeger.yaml

Ref. https://grafana.com/docs/grafana/latest/visualizations/node-graph/
https://github.com/grafana/grafana/blob/main/docs/sources/datasources/loki.md#configure-the-data-source-with-provisioning

Add Jaeger Node graphs

---

manifests/argocd-apps/prd/grafana.yaml
manifests/argocd-apps/prd/jaeger.yaml

add node graphs in production

---

manifests/argocd-apps/prd/grafana.yaml

Add Grafana security in prd

---

manifests/app/dreamkast/overlays/production/main/ingress.yaml

update HTTPProxy setting for cookie's secure attribute

---

manifests/argocd-apps/dev/aws-load-balancer-controller.yaml

update lb controller dev

---

manifests/argocd-apps/prd/aws-load-balancer-controller.yaml

update lb controller prd

---

manifests/argocd-apps/prd/grafana.yaml

ref: [cloudnativedaysjp/observability#53](https://github.com/cloudnativedaysjp/observability/issues/53)

prod: Add #cnsec2022 proposals dashboard

---

manifests/argocd-apps/prd/grafana.yaml

Update: update dashboard

---

dashboards/cnsec2022-cfp.json

Update cnsec2022-proposal dashborad

---

cfn/ecr-lifecycle-policy.yaml

現時点だとmainタグがついているものもこのルールによって消えてしまうので、ワークアラウンドとしてルールを削除。
Fixes #1257

Remove rule for workaround

---

dashboards/cnsec2022-main.json
manifests/argocd-apps/dev/grafana.yaml

[Issue](https://github.com/cloudnativedaysjp/observability/issues/57)

dev: Add CNSec2022 dashboard

---

manifests/argocd-apps/dev/falco.yaml

Add Helm options to Falco chart

---

manifests/argocd-apps/prd/falco-certs.yaml
manifests/argocd-apps/prd/falco-exporter-certs.yaml
manifests/argocd-apps/prd/falco-exporter.yaml
manifests/argocd-apps/prd/falco.yaml
manifests/argocd-apps/prd/grafana.yaml

Fixes [observability - #58](https://github.com/cloudnativedaysjp/observability/issues/58)

prod: Feature/add falco prod

---

manifests/argocd-apps/prd/grafana.yaml

- ダッシュボードの更新に伴い、URLのハッシュ値を変更しました.
- https://raw.githubusercontent.com/cloudnativedaysjp/dreamkast-infra/5b182de9a1071626932d3aa7325933a0bb3c6408/dashboards/cnsec2022-cfp.json
- 前回のカンファレンス(o11y Conn)のメトリクスは現在、消えているため、ダッシュボードを非表示にしました.
- https://github.com/cloudnativedaysjp/observability/issues/61

Update: Update grafana dashboard url "cnsec2022 proposals"

---

manifests/argocd-apps/prd/grafana.yaml

prod: Added cnsec2022 main dashboard to prod

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

Update path in httpproxy resources for CNSec2022
Fixes https://github.com/cloudnativedaysjp/dreamkast/issues/1301

Update path for CNSec2022

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Reduce instances

---

manifests/argocd-apps/dev/grafana.yaml

@jacopen からの Grafana の脆弱性の報告をいただき、バージョンアップの対応を行った.
- https://github.com/grafana/grafana/security/advisories/GHSA-mx47-6497-3fv2
- https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1658515479023159

Dev: Update image and chart version of Grafana

---

manifests/argocd-apps/prd/grafana.yaml

#1760 に伴いダッシュボードのハッシュ値が変わったので修正

ダッシュボード変更に伴いハッシュ値変更

---

manifests/argocd-apps/prd/grafana.yaml

#1761 でDevのバージョンアップに成功したのでprod環境にも適用

Prod: Update Grafana Verision on prod/grafana.yaml

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Increase replicas

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

change number of replicas

---

manifests/argocd-apps/dev/falco.yaml
manifests/argocd-apps/prd/falco.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1797

Revert "update falco"

---

manifests/argocd-apps/dev/loki.yaml
manifests/argocd-apps/dev/metrics-server.yaml
manifests/argocd-apps/prd/loki.yaml
manifests/argocd-apps/prd/metrics-server.yaml

update loki and metrics server

---

cfn/eks-nodes-bottlerocket.yaml

https://github.com/cloudnativedaysjp/dreamkast/pull/1345 https://github.com/cloudnativedaysjp/dreamkast/issues/1317 でIVS/MediaLiveなどのリージョンを変えるので、それに合わせて権限を追加する。既存のリソースへのアクセスを可能にするためus-east-1へのアクセス権限は残す。

allow to access SSM Parameters in tokyo region

---

manifests/argocd-apps/prd/aws-ebs-csi-driver.yaml

upgrade csi driver on prod

---

manifests/argocd-apps/dev/aws-load-balancer-controller.yaml

update lb controller

---

manifests/argocd-apps/prd/aws-load-balancer-controller.yaml

update prd lbc

---

manifests/infra/contour/base/kustomization.yaml

update contour to 1.21.1

---

manifests/argocd-apps/prd/cert-manager.yaml

update cert-manager on prd

---

manifests/argocd-apps/dev/cert-manager.yaml
manifests/argocd-apps/prd/cert-manager.yaml

update to 1.9.1

---

manifests/infra/contour/base/kustomization.yaml

contour to 1.22

---

manifests/argocd-apps/dev/falco-exporter.yaml
manifests/argocd-apps/dev/falco.yaml

Fixes [observability - #64](https://github.com/cloudnativedaysjp/observability/issues/64)

[dev] update falco version

---

manifests/argocd-apps/dev/falco.yaml

test initContainers securityContext

---

manifests/infra/contour/base/contour-configmap.yaml
manifests/infra/contour/base/gatewayclass.yaml
manifests/infra/contour/base/kustomization.yaml

Static provisioningの方法でGateway APIを使えるようにする
ref. https://projectcontour.io/guides/gateway-api/#testing-the-gateway-api

install gateway api

---

manifests/argocd-apps/prd/falco-exporter.yaml
manifests/argocd-apps/prd/falco.yaml

Fixes [observability - #64](https://github.com/cloudnativedaysjp/observability/issues/64)

[Prod] Update falco chart version

---

manifests/reviewapps/dreamkast-dk_codt2022.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast-ui_codt2022.yaml

fix reviewapps

---

manifests/argocd-apps/dev/falco-exporter.yaml

ArgoCDで同期をとるためのダミーコミットです。動作確認後、リバートします

[dev] ArgoCDをキックするためのダミーコミット

---

manifests/argocd/overlays/dev/argocd-rbac-cm.yaml
manifests/argocd/overlays/prd/argocd-rbac-cm.yaml

Add olly-core team as admin

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml

Add New Relic License Key env

---

manifests/argocd-apps/dev/aws-cluster-autoscaler.yaml
manifests/argocd-apps/dev/aws-ebs-csi-driver.yaml
manifests/argocd-apps/prd/aws-cluster-autoscaler.yaml
manifests/argocd-apps/prd/aws-ebs-csi-driver.yaml

update aws charts

---

manifests/infra/telegraf/base/deployment.yaml
manifests/infra/telegraf/overlays/development/kustomization.yaml
manifests/infra/telegraf/overlays/development/patch-telegraf-deployment.yaml

dev環境でのdreamkastのデータのprometheusへの抽出対象をCNSEC2022からCNDT2022に更新します
<s>dev/prod両方更新されるため、すぐにマージして問題ないか気になっています。</s>
→とりあえずdev環境だけ更新するように変更
refs : https://github.com/cloudnativedaysjp/cndt2022/issues/39 #1668

Update config of telegraf to CNDT2022 conf_id

---

manifests/infra/telegraf/overlays/development/kustomization.yaml
manifests/infra/telegraf/overlays/development/patch-configmap.yaml

新しいCNDT2022で追加された新しいsession_time と languageのlabelを取り込む
とりあえずdevelopmentでお試し
変更点はここだけ
```
> diff manifests/infra/telegraf/base/configmap.yaml manifests/infra/telegraf/overlays/development/patch-configmap.yaml
2d1
< 
101c100
<         query="SELECT t.id AS talk_id,p.label,p.params FROM proposal_items p LEFT JOIN talks t ON p.talk_id = t.id  WHERE ( p.label = 'presentation_method' OR p.label = 'assumed_visitor' OR p.label = 'execution_phase' OR p.label = 'whether_it_can_be_published') AND p.conference_id='${CONF_ID}'"
---
>         query="SELECT t.id AS talk_id,p.label,p.params FROM proposal_items p LEFT JOIN talks t ON p.talk_id = t.id  WHERE p.label in ('presentation_method', 'assumed_visitor','execution_phase','whether_it_can_be_published','session_time','language') AND …
```

Update telegraf-config for development

---

manifests/argocd-apps/dev/falco.yaml

enabled falco sidekick

---

manifests/argocd-apps/dev/falco.yaml

disable filcosidekick

---

manifests/argocd-apps/dev/falco-sidekick.yaml
manifests/argocd-apps/dev/falco.yaml

add falco-sidekick argo application

---

manifests/infra/telegraf/overlays/development/patch-configmap.yaml

refs: https://github.com/cloudnativedaysjp/cndt2022/issues/39
refs: #50
telegrafの設定を修正します。
影響範囲はdev環境のみです
mysqlのクエリは問題なさそうで、labelとparamsでサマライズされてそうなので、talk_idを追加してみました。
```
mysql> SELECT t.id AS talk_id,p.label,p.params FROM proposal_items p LEFT JOIN talks t ON p.talk_id = t.id  WHERE p.label in ('session_time') AND p.conference_id='7';
+---------+--------------+--------+
| talk_id | label        | params |
+---------+--------------+--------+
|    1421 | session_time | "76"   |
|    1422 | session_time | "76"   |
|    1423 | session_time | "76"   |
|    1424 | session_time | "77"   |
|    1425 | session_time | "76"   |
|    1426 | session_time | "77"   |
|    1427 | session_time | "77"   |
|    1428 | session_time | "76"   |
|    1429 | session_time | "77"   | …
```

Change telegraf config for dev

---

manifests/argocd-apps/prd/falco-sidekick.yaml
manifests/argocd-apps/prd/falco.yaml

[Prod] Added falco sidekick and web ui

---

manifests/app/chatbot/configmap.yaml

chatbotのtargetsにdreamkast-functionsを追加

---

manifests/app/argocd-apps/production/seaman.yaml

rename Repository name: chatbot > seaman

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml

- CFP投票機能実装にあたり環境変数を追加したので、manifestにも追加
- https://github.com/cloudnativedaysjp/dreamkast/pull/1491#discussion_r979388519

API Gatewayのアドレスを環境変数に追加

---

manifests/argocd-apps/dev/grafana.yaml

add argocd dashboard to public

---

manifests/argocd-apps/prd/grafana.yaml

add argocd dashboard to prd

---

dashboards/github.json
manifests/argocd-apps/dev/grafana.yaml

Github Issuesが見れるダッシュボードを作ってみました。
ただグラフを置くだけだと寂しいので、できる範囲で少しでも見栄えするようにしています。

Add Grafana Dashboard to show Github issues

---

.github/renovate.json5
renovate.json

NO-ISSUE
* update renovate conf as below
* grouping with each package
* make renovate detect ArgoCD Application yaml

update renovate conf

---

manifests/argocd-apps/dev/prometheus-pushgateway.yaml

Added prometheus push gateway

---

manifests/argocd-apps/dev/prometheus-pushgateway.yaml

Change scrape interval

---

manifests/app/dreamkast/overlays/development/template-dk/.patch_deployment-strategy.yaml
manifests/app/dreamkast/overlays/development/template-dk/kustomization.yaml
manifests/app/dreamkast/overlays/development/template-ui/.patch_deployment-strategy.yaml
manifests/app/dreamkast/overlays/development/template-ui/kustomization.yaml

No Issue
Specify `strategy: Recreate` to ensure that the ReviewApps' target Pods are updated.

NO-ISSUE: Specify 'strategy: Recreate' to all ReviewApp's manifests

---

dashboards/cndt2022-main.json
manifests/argocd-apps/dev/grafana.yaml

CNDT2022のメインダッシュボードを新規作成
Fixes: none

add: CNDT2022メインダッシュボードを追加

---

manifests/argocd-apps/dev/aws-cluster-autoscaler.yaml
manifests/argocd-apps/prd/aws-cluster-autoscaler.yaml

Ref. https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml#L294

add resource requests and limits on CA

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/development/template-dk/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

dk-uiの方のハードコードは直しましたが、manifest側を忘れていたので、s/cnsec2022/cndt2022 しました。

Replace cnsec2022 hardcodes to cndt2022

---

manifests/infra/social-analysis/base/deployment.yaml

fix social tags

---

manifests/infra/social-analysis/base/deployment.yaml

Social AnalysisでWordCount対応を行ったので、その反映です

Bump up social analysis version 0.0.1 to 0.0.2

---

manifests/argocd-apps/dev/grafana.yaml

add wordcloud plugin for grafana

---

dashboards/cndt2022-main.json

add wordcloud panel

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

Decrease HPA for production 

---

manifests/argocd/base/kustomization.yaml

Upgrade argocd to address CVE

---

manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-ui.yaml

dk-ui stagingのbackendを、dk直からapi gatewayに変更しました。
これをmergeするまえに、先にapi gateway側のPRをmergeしてください。
https://github.com/cloudnativedaysjp/dreamkast-functions/pull/42#pullrequestreview-1169433612

Change api backend of dk-ui staging

---

manifests/argocd-apps/dev/prometheus-pushgateway.yaml

[Dev] Handle TLS

---

manifests/argocd-apps/dev/prometheus-pushgateway.yaml

[Dev] Fixed secretName

---

manifests/argocd-apps/dev/prometheus-pushgateway-ingress.yaml
manifests/argocd-apps/dev/prometheus-pushgateway.yaml
manifests/infra/pushgateway-ingress/overlays/development/ingress.yaml

Handle TLS

---

manifests/infra/social-analysis/base/deployment.yaml

update social analysis to 1.0.0

---

manifests/argocd-apps/prd/prometheus-pushgateway-ingress.yaml
manifests/argocd-apps/prd/prometheus-pushgateway.yaml
manifests/infra/pushgateway-ingress/overlays/production/ingress.yaml

[Prod] Handle TLS

---

manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml

dk-uiの検証でlocal devからstaging APIを叩けるようにするために、stagingに限りcorsを全開放します。
stagingに環境変数を一つ設定するだけなので、直mergeさせてください（検証してだめだったらrevertします）

Allow any origin to access dreamkast on staging

---

manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml

間違えてinitContainerの方に追加してしまっていたので、直しました

fixup! Allow any origin to access dreamkast on staging

---

manifests/argocd-apps/dev/grafana.yaml

検証用にCloud watchのカスタムメトリクスを取得する設定をいれたいです。
動作検証はできてないです。マージ後に動作確認し問題あればRevertか修正用のPR書く予定です。
設定は[Datasources](https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources)のJSON Dataを参照しました。
設定値はCloudWatch側で作成済みのカスタムメトリクスのNamespaceの名前になります。
https://us-west-1.console.aws.amazon.com/cloudwatch/home?region=us-west-1#metricsV2:graph=~()

feat: add customMetricsNamespaces for dreamkast-functions to grafana

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml
manifests/argocd-apps/prd/keda.yaml
manifests/infra/keda-external-scalers/overlays/production/dreamkast-external-scaler.yaml
manifests/infra/keda-external-scalers/overlays/production/kustomization.yaml

No Issues
* related PRs: #2071

Install & Enable keda on production dreamkast

---

manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/development/template-ui/externalsecret.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/staging/main/secret.yaml

https://github.com/cloudnativedaysjp/dreamkast-ui/pull/337
を動かすのに必要な環境変数の追加です。

NEXT_PUBLIC_EVENT_SALT env var

---

dashboards/cndt2022-onsite.json
manifests/argocd-apps/dev/grafana.yaml

CNDT2022のオンサイト用のダッシュボードを追加しました。
ひとまずdevのPublicに公開するPRになります。
作成した画面はこちらになります。
https://grafana.dev.cloudnativedays.jp/d/pQyLdgd4z/cndt2022-onsite-dashboard-experimental
people countの部分は現地に行ってカメラを設置しないと書けないのかなと思ってひとまず保留にしています。

CNDT2022オンサイト用ダッシュボードの追加

---

manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/service.yaml

- ui用のサービスがなくなっていたので追加
- dreamkast本体はuiのReviewAppから消したのでConditionから削除

Fix UI reviewapp

---

manifests/app/dreamkast/overlays/development/template-ui/kustomization.yaml

add service.yaml

---

manifests/infra/social-analysis/base/deployment.yaml

Bump up version 1.0.1

---

dashboards/cndt2022-main.json

fix font cloud

---

manifests/argocd-apps/prd/grafana.yaml

CNDT2022 main, onsiteをprodに反映

---

manifests/argocd-apps/prd/grafana.yaml

add word cloud plugin for grafana

---

manifests/argocd-apps/prd/grafana.yaml

[Prod] Change dashboard

---

manifests/argocd-apps/prd/grafana.yaml

Update prd cndt2022-cfp

---

dashboards/cndt2022-onsite-monitor.json
manifests/argocd-apps/dev/grafana.yaml

オンサイトのラズパイが動いているかを確認するダッシュボードです。
https://grafana.cloudnativedays.jp/d/CBYDgTd4z/onsaitojian-shi-yong?orgId=1

Onsite Monitor Dashboardの作成

---

manifests/argocd-apps/prd/grafana.yaml

こちらのjsonをprodへ反映させるPRです。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/dashboards/cndt2022-onsite-monitor.json
画面は[こちら](https://grafana.dev.cloudnativedays.jp/d/CBYDgTd4z/onsaitojian-shi-yong)

Onsite Monitor Dashboardをprodへ反映

---

manifests/argocd/base/kustomization.yaml

Ref. https://github.com/argoproj/argo-cd/releases/tag/v2.5.3

Update argocd to 2.5.3

---

dashboards/cndt2022-onsite.json

pushgateway経由のprometheus metricには、labelにpushgatewayのpod名が入っています。
このためpushgatewayがrestartした際にgrafanaのグラフが別れちゃう問題を修正します
修正前
修正後
metricはこんな感じ
```
co2_conce{container="pushgateway", endpoint="http", job="co2", namespace="monitoring", pod="prometheus-pushgateway-6f7c899477-smvrz", service="prometheus-pushgateway"}
```

Fix cndt2022-onsite dashboard

---

.github/renovate.json5
manifests/argocd/base/kustomization.yaml
manifests/infra/prometheus/base/kustomization.yaml

make manifest's version written in kustomization.yaml be updated automatically by renovate.
In my repository for verification, I confirmed to be created PR for update manifests.
* https://github.com/ShotaKitazawa/verification_renovate

Add regexManagers on renovate

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml

SLACK_TOKENを渡すように修正。secretsには登録済み。

参加者登録数通知が動いていない問題を修正

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml
manifests/infra/mysql-o11y/overlays/production/cronjob.yaml

Revert mysql container image back to pre-patch

---

manifests/infra/social-analysis/base/deployment.yaml

イベントに合わせハッシュタグをアップデートしました（`#CNDT2022*` → `#CICD2023`）

Update Twitter hashtag CNDT2022 to CICD2023

---

dashboards/cicd2023-main.json
manifests/argocd-apps/dev/grafana.yaml

- Dev環境のGrafanaにCI/CD2023のメインダッシュボードを追加
- ファイル名を半角区切りで管理していたが、以下の理由から変更した
- 指定しているファイル名とディレクトリ内に保存されるファイル名(半角スペースが入った状態で保存)に統一性がないため
- コマンドなどの実行時に`\`を打つ必要があるなどの不便さがあったため

Add: Add dashboard "CI/CD2023 Dashboard"

---

manifests/argocd-apps/prd/grafana.yaml

- Dev環境のGrafanaにCI/CD2023のメインダッシュボードを追加
- ファイル名を半角区切りで管理していたが、以下の理由から変更した
- 指定しているファイル名とディレクトリ内に保存されるファイル名(半角スペースが入った状態で保存)に統一性がないため
- コマンドなどの実行時に`\`を打つ必要があるなどの不便さがあったため

Add: Add dashboard "CI/CD2023 Dashboard" for Production

---

manifests/app/dreamkast/overlays/development/template-dk/delete-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/development/template-dk/kustomization.yaml

fix: Remove dk-ui deploy/svc from dk reviewapps

---

manifests/argocd-apps/dev/loki.yaml

- 以下の問題を解決するために、LokiのRetention機能を有効化することにした
- https://github.com/cloudnativedaysjp/observability/issues/76
- Retentionの期限としては、そこまで長期保存する必要性が現状ないため、1week(168H)に設定した

Enable Loki's Retention function for Dev

---

manifests/argocd-apps/dev/grafana.yaml

- 以前、不具合により有効化していたオプションを検証のため無効化
- https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1536

Disable "disableDeletion" for Dev

---

manifests/app/dreamkast/base/pdb.yaml

change policy/v1beta1 to policy/v1

Change api version of pdb

---

manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-ui.yaml

fix: staging's DK_URL

---

manifests/argocd-apps/dev/contour.yaml

4/23の定例で会話させていただきましたが、contourの設定検証をするにあたり、検証環境のautosyncを一時的に無効にさせていただきたいです 🙇

検証環境のcountourのautosyncを一時的に無効化

---

manifests/app/argocd-apps/development/dreamkast-staging.yaml
manifests/argocd-apps/dev/cert-manager.yaml
manifests/argocd-apps/dev/dreamkast.yaml
manifests/argocd-apps/dev/mysql-o11y.yaml
manifests/argocd-apps/dev/prometheus-ingress.yaml
manifests/argocd-apps/dev/reviewapps.yaml
manifests/argocd-apps/dev/telegraf.yaml
manifests/reviewapps/dreamkast-dk.yaml

When migrating development environment, dreamkast_us branch was created for parallel operation, merged into the main branch, so argo's destination is reverted back to the original.

argo distination to main branch

---

manifests/application-dev.yaml

chore: mainへ戻す修正し忘れ

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml

bump up mysql o11y

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml

fix: specify even the mysql patch version

---

manifests/infra/mysql-o11y/overlays/production/cronjob.yaml

fix: specify even the mysql patch version for production

---

manifests/argocd-apps/dev/contour.yaml
manifests/infra/contour/overlays/development/lb-internet-facing.yaml

dk-weaverのCFP投票機能では、クライアントIPを使用した投票制限機能を実装しており、コンテナ内でクライアントのIPアドレスを取得できる必要があります。そのため、LoadBalancerの`クライアントIPアドレスの保持`を有効にし、コンテナ内でIPアドレスが取得できるようにしました。また、一時的に無効にしていたAutoSyncも有効にしました。
`クライアントIPアドレスの保持`を有効にしたLoadBalancerは、ArgoCDやDreamkastといったトラフィックも通っているため、設定変更による影響範囲が広くなっています。NLBの料金が(意外と？)安く、2台目を作成することも考えましたが、Manifest管理が若干複雑になるかつ影響内容に比べてメリットが小さいと考えやめました。
FYI：
- [Load Balancer Target Groups: Client IP preservation](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#client-ip-preservation)
- [AWS Load Balancer Controller Annotations: Resource Attributes](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#resource-attributes)
httpbinサービスをデプロイしてコンテナ内でクライアントのIPアドレスが取得できることを確認しました。
- httpbinのManifest
<details> …

feat: Enable preserve_client_ip in contour

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml

Reviewapp環境で立ち上がるdkの環境変数に`DREAMKAST_WEAVER_ADDR`を追加しました。
- ref: https://github.com/cloudnativedaysjp/dreamkast/pull/1899/files

feat: Add DREAMKAST_WEAVER_ADDR to dk in reviewapp

---

manifests/app/seaman/configmap.yaml

As part of https://github.com/cloudnativedaysjp/seaman/blob/main/docs/release.md

Add emtec-ecu to seaman

---

manifests/argocd-apps/dev/cert-manager.yaml

Dev環境の`cert-manager`のイメージを更新
Fixes #2465, https://github.com/cloudnativedaysjp/observability/issues/89

Update: Update cert-manager image of dev

---

manifests/argocd-apps/dev/keda.yaml

Dev環境の`keda`のイメージを更新
Fixes #2465, https://github.com/cloudnativedaysjp/observability/issues/89

Update: Update keda image for dev

---

manifests/argocd-apps/dev/falco-exporter.yaml

Dev環境の`falco-exporter`のイメージを更新
Fixes #2465, https://github.com/cloudnativedaysjp/observability/issues/89

Update: Update falco-exporter images of dev

---

manifests/argocd-apps/dev/falco.yaml

Dev環境の`falco`のイメージを更新
Fixes #2465, https://github.com/cloudnativedaysjp/observability/issues/89

Update: Update falco image for dev

---

manifests/argocd-apps/dev/aws-load-balancer-controller.yaml

ref. https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2516

chore(deps): for dk-dev: update Helm release aws-load-balancer-controller to v1.5.2

---

manifests/argocd-apps/prd/grafana.yaml

ダッシュボード追加時に自動的に反映されるように修正しました
https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2393

Change properties for UI updates

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/development/template-dk/viewer-count.yaml
manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/production/main/viewer-count.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/viewer-count.yaml

use self-hosted sentry

---

manifests/app/dreamkast/base/deployment.yaml

prepare sentry for weaver

---

manifests/app/seaman/configmap.yaml

Add dk-weaver to seaman

---

manifests/infra/contour/base/kustomization.yaml
manifests/infra/contour/overlays/development/kustomization.yaml

contourのmanifestで`kustomize build`に失敗していたので修正しました
- 修正前
```
$ kustomize build overlays/development/ | head
Error: accumulating resources: accumulation err='accumulating resources from '../../base': '/data/ghq/github.com/cloudnativedaysjp/dreamkast-infra/manifests/infra/contour/base' must resolve to a file': recursed accumulation of path '/data/ghq/github.com/cloudnativedaysjp/dreamkast-infra/manifests/infra/contour/base': no matches for Id ConfigMap.v1.[noGrp]/contour.projectcontour; failed to find unique target for patch ConfigMap.v1.[noGrp]/contour.projectcontour
```
- 修正後
```
$ kustomize build overlays/development/ | head
apiVersion: v1
kind: Namespace
metadata:
name: projectcontour
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
annotations: …
```

fix: Rollback to f901ddd

---

manifests/argocd/overlays/dev/pods.yaml
manifests/argocd/overlays/prd/pods.yaml

increase resource limits for Argo CD

---

manifests/app/seaman/configmap.yaml
manifests/app/seaman/deployment.yaml
manifests/app/seaman/ingress.yaml
manifests/app/seaman/secret.yaml
manifests/app/seaman/service.yaml

seaman v1.0.0 supports GitHub Webhook. So I created Service & Ingress manifests, and updated existing manifests for additional variables.

update for seaman v1.0.0

---

manifests/infra/argocd-apps/development/falco-exporter.yaml
manifests/infra/argocd-apps/production/falco-exporter.yaml

Update Helm release falco-exporter to v0.9.6

---

manifests/infra/argocd-apps/production/aws-cluster-autoscaler.yaml

Update Helm release cluster-autoscaler to v9.29.0

---

manifests/infra/argocd-apps/production/aws-load-balancer-controller.yaml

chore(deps): update helm release aws-load-balancer-controller to v1.5.3

---

manifests/app/dreamkast/overlays/development/template-dk/delete-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/development/template-dk/kustomization.yaml

- template-dk内のdk-weaverがImagePullBackoff状態になるので削除しました
- template-dk内のdk自体はstgのdk-weaverを参照しており、現状だれからも参照されていないリソースになります
- dk-uiと同様の対応です

template-dkからdreamkast-weaverを削除

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml

Add OTEL_SERVICE_NAME

---

manifests/infra/contour/overlays/production/kustomization.yaml

chore(deps): update dependency projectcontour/contour to v1.25.0

---

manifests/app/dreamkast/overlays/staging/main/ingress.yaml

[staging] add healthCheckPolicy for readinessProbe

---

manifests/infra/argocd-apps/development/falco-exporter.yaml
manifests/infra/argocd-apps/production/falco-exporter.yaml

Fix repository location of images to be retrieved.

Fix: Change image repository

---

manifests/infra/argocd-apps/production/aws-ebs-csi-driver.yaml

Update Helm release aws-ebs-csi-driver to v2.19.0

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/development/template-dk/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

rename path to cndf2023

---

manifests/infra/argocd-apps/development/grafana.yaml

- Grafanaにプラグインを追加
- GrafanaでGoogle Analyticsの情報を可視化するため
- https://grafana.com/grafana/plugins/blackcowmoo-googleanalytics-datasource/

Add: Add plugin

---

dashboards/cndf2023-main.json
manifests/infra/argocd-apps/development/grafana.yaml

Add: Add dashboard "CNDF2023 Dashboard" (Dev)

---

manifests/infra/argocd-apps/production/grafana.yaml

- Production環境にGrafanaダッシュボードを追加

Add: Add dashboard "CNDF2023 Dashboard" (Prod)

---

dashboards/cndf2023-main.json

Fix: Fix dashboard "CNDF2023 Dashboard" (Dev)

---

manifests/infra/argocd-apps/production/grafana.yaml

Fix: Fix dashboard "CNDF2023 Dashboard" (Prod) 

---

manifests/app/dreamkast/overlays/development/template-weaver/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

- dk-weaverには`_session_id`なるCookieはないので、cookieRewritePoliciesを削除する
- FYI : https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2686#discussion_r1247641679 
- [x ] I have checked backward/forward compatibility that may cause regarding this change.

feat: delete cookieRewritePolicies in dk-weaver

---

manifests/app/argocd-apps/development/dreamkast-staging.yaml
manifests/application-dev.yaml
manifests/argocd-apps/development/dreamkast.yaml
manifests/argocd-apps/development/infra.yaml
manifests/infra/argocd-apps/development/contour.yaml
manifests/infra/argocd-apps/development/falco-exporter.yaml
manifests/infra/argocd-apps/development/falco.yaml
manifests/infra/argocd-apps/development/gateway-api.yaml
manifests/infra/argocd-apps/development/grafana.yaml
manifests/reviewapps/dreamkast-dk.yaml

fix targetRevision

---

manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-ui.yaml

dk-uiからdk-weaverを叩くための環境変数を追加しました。
各環境のendpointがあっているか、確認してもらえると助かります。

feat(dk-ui): Add NEXT_PUBLIC_WEAVER_URL env var

---

dashboards/falco-dashboard.json

現状のダッシュボードでは、イベントがどのPodで発生したかが確認しにくいため、Table Viewを更新しました
問題なさそうであれば、Prodにも導入します
[observability #66](https://github.com/cloudnativedaysjp/observability/issues/66)
https://grafana.dev.cloudnativedays.jp/d/FvUFlfuZz/falco-dashboard?orgId=1&refresh=30s

[dev] Customize falco dashboard

---

manifests/infra/argocd-apps/development/aws-cluster-autoscaler.yaml
manifests/infra/argocd-apps/development/aws-ebs-csi-driver.yaml
manifests/infra/argocd-apps/development/aws-load-balancer-controller.yaml
manifests/infra/argocd-apps/development/falco-exporter.yaml
manifests/infra/argocd-apps/development/falco.yaml
manifests/infra/argocd-apps/development/keda.yaml
manifests/infra/argocd-apps/production/aws-cluster-autoscaler.yaml
manifests/infra/argocd-apps/production/aws-ebs-csi-driver.yaml
manifests/infra/argocd-apps/production/aws-load-balancer-controller.yaml
manifests/infra/argocd-apps/production/falco-exporter.yaml
manifests/infra/argocd-apps/production/falco.yaml
manifests/infra/argocd-apps/production/keda.yaml
manifests/infra/external-snapshotter/overlays/development/kustomization.yaml
manifests/infra/external-snapshotter/overlays/production/kustomization.yaml
manifests/infra/keda-external-scalers/overlays/development/dreamkast-external-scaler.yaml
manifests/infra/keda-external-scalers/overlays/production/dreamkast-external-scaler.yaml
manifests/infra/prometheus/base/alertmanager.yaml
manifests/infra/prometheus/overlays/development/kustomization.yaml
manifests/infra/prometheus/overlays/development/prometheus.yaml

* adjust QoS on some Pods
* remove external-snapshotter controller
* because it's contained in aws-ebs-csi-driver as sidecar

adjust Pod QoS

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/development/template-weaver/deployment-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-weaver.yaml

- 下記PRで追加したenvをdk-weaverに追加しました
- https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/37
- https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/46
- IVSはこちらを参考にしました
- https://github.com/cloudnativedaysjp/dreamkast/blob/v3.10.14/app/models/live_stream_ivs.rb#L109-L114
- 念のためSlackでも確認済み：https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1689588508043309

feat: Add env in dk-weaver

---

manifests/infra/argocd-apps/development/grafana.yaml

- GrafanaのAdmin権限を付与するロールグループを変更

Fix: Fix Grafana role admin

---

dashboards/cndf2023-main.json

ダッシュボードに表示する視聴者数の取得元を変更しました
- STGで確認しましたが、良さそうでした

fix: Switching the source of viewer-count to dk-weaver

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml

Update sentry dsn

---

manifests/infra/argocd-apps/development/kubernetes-event-exporter.yaml
manifests/infra/kubernetes-event-exporter/base/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/base/kustomization.yaml

Add argo apps that kubernetes event exporter

---

manifests/infra/argocd-apps/production/grafana.yaml

- PRDのダッシュボードを更新しました！
- see: https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2735#issuecomment-1655715819

chore: Update dashbord for cndf2023

---

manifests/infra/argocd-apps/development/grafana.yaml

Sentry VMに構築したPrometheusをDataSourceに追加する設定です。
追加されたら、諸々のダッシュボードの構築を行います

Add datasource for Sentry

---

dashboards/sentry-kafka.json
dashboards/sentry-postgresql.json
dashboards/sentry-redis.json
manifests/infra/argocd-apps/development/grafana.yaml

Self hosted Sentryの監視用にDashboardを追加しました
- Redis: [https://grafana.dev.cloudnativedays.jp/d/bRd48yKMdd/redis-sentry](https://grafana.dev.cloudnativedays.jp/d/bRd48yKMdd/redis-sentry)
- Kafka: [https://grafana.dev.cloudnativedays.jp/d/jwPKIsniz/kafka-sentry](https://grafana.dev.cloudnativedays.jp/d/jwPKIsniz/kafka-sentry)
- PostgreSQL: [https://grafana.dev.cloudnativedays.jp/d/wGgaPlciz/postgresql-sentry](https://grafana.dev.cloudnativedays.jp/d/wGgaPlciz/postgresql-sentry)

Add dashboards for Self hosted Sentry

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/production/main/viewer-count.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/viewer-count.yaml

- dk検証会を踏まえ、下記の対応を実施しました
- envの修正
- CronJobの追加
- devは不要な気がしたので追加していません
- 設定値は全てキメです
- see: https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1690542683825049

Viewer Countを定期実行するCronJobの追加

---

dashboards/cnd-deep-dive.json
dashboards/dk-deep-dive.json
manifests/infra/argocd-apps/development/grafana.yaml

Google Analyticsのダッシュボードを追加しました
- Dreamkast Deep Dive
- https://grafana.dev.cloudnativedays.jp/d/u5sXIaqVk/dreamkast-deep-dive?orgId=1
- CloudNativeDays Deep Dive
- https://grafana.dev.cloudnativedays.jp/d/I5GV5V34k/cloudnativedays-deep-dive?orgId=1

Add: Add GA dashboards

---

manifests/infra/argocd-apps/development/grafana.yaml

Fix: typo miss

---

manifests/infra/argocd-apps/production/grafana.yaml

Add: Add GA dashboards to production

---

manifests/infra/argocd-apps/production/grafana.yaml

Add: Add datasource

---

manifests/infra/argocd-apps/production/grafana.yaml

- ダッシュボードのコミットハッシュを変更
- ロールの参照先を変更

Update: Update commit hash

---

manifests/app/dreamkast/overlays/production/main/hpa.yaml

- dk-weaverにHPCの設定いれました（入れ忘れてました...
- dk-uiの設定が入っていないのと、STGでも設定するべきか悩んだので、一旦STGの設定はいれてません

feat: Add hpc for dk-weaver

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml

FIx: Chage DSN

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml

Fix: typomiss

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml
manifests/infra/argocd-apps/development/grafana.yaml

Fix: Change dsn on stg

---

manifests/infra/argocd-apps/production/kubernetes-event-exporter.yaml
manifests/infra/kubernetes-event-exporter/base/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/overlays/development/kustomization.yaml
manifests/infra/kubernetes-event-exporter/overlays/development/patch.yaml
manifests/infra/kubernetes-event-exporter/overlays/production/kustomization.yaml
manifests/infra/kubernetes-event-exporter/overlays/production/patch.yaml

Add k8s event exporter app to prodcution

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml

Change sentry dsn

---

manifests/infra/argocd-apps/development/grafana.yaml

Change datasource dns

---

manifests/infra/argocd-apps/production/grafana.yaml

本番GrafanaにもSentry用のDashboard追加しました

Add datasource and dashboard for sentry

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml

PostgreSQLの分離でDSNが変わったので、再設定しました

Change DSN

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/argocd-apps/production/grafana.yaml

fix sentry dashboard

---

manifests/infra/argocd-apps/development/grafana.yaml

dk-functionsを削除するので、カスタムメトリクスの取得設定を削除しました

chore: Remove DrcustomMetricsNamespaces for DreamKaktFunctions

---

manifests/infra/argocd-apps/development/promtail.yaml

Add promtail to dev env

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/argocd-apps/production/grafana.yaml

- GrafanaにBigQueryのプラグインを追加
- https://grafana.com/grafana/plugins/grafana-bigquery-datasource/?tab=overview

Add: Add BigQuery plugin (Dev and Prod)

---

manifests/app/dreamkast/base/secret.yaml
manifests/app/dreamkast/overlays/development/template-dk/externalsecret.yaml
manifests/app/dreamkast/overlays/development/template-ui/externalsecret.yaml
manifests/app/dreamkast/overlays/development/template-weaver/delete-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml
manifests/app/dreamkast/overlays/staging/main/secret.yaml
manifests/app/seaman/secret.yaml
manifests/infra/argocd-apps/development/external-secrets.yaml
manifests/infra/argocd-apps/production/external-secrets.yaml
manifests/infra/grafana/overlays/development/externalsecret.yaml
manifests/infra/grafana/overlays/production/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/base/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/base/kustomization.yaml
manifests/infra/kubernetes-event-exporter/overlays/development/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/overlays/development/kustomization.yaml
manifests/infra/kubernetes-event-exporter/overlays/development/patch.yaml
manifests/infra/kubernetes-event-exporter/overlays/production/externalsecret.yaml
manifests/infra/kubernetes-event-exporter/overlays/production/kustomization.yaml
manifests/infra/kubernetes-event-exporter/overlays/production/patch.yaml
manifests/infra/mysql-o11y/overlays/development/secret.yaml
manifests/infra/mysql-o11y/overlays/production/secret.yaml
manifests/infra/prometheus-ingress/overlays/development/secret.yaml
manifests/infra/prometheus-ingress/overlays/production/secret.yaml
manifests/infra/prometheus/overlays/development/slack-secrets.yaml
manifests/infra/telegraf/overlays/development/secrets.yaml
manifests/infra/telegraf/overlays/production/secrets.yaml

Fixes https://github.com/cloudnativedaysjp/dreamkast/issues/1993

update for migrating external-secrets from KES to ESO

---

manifests/infra/argocd-apps/production/keda.yaml

Enable SSA on keda

---

manifests/infra/argocd-apps/development/prometheus.yaml
manifests/infra/argocd-apps/production/prometheus.yaml

- PrometheusのArgoCDの同期オプションにSSAを有効化するオプションを追加
https://argo-cd.readthedocs.io/en/latest/proposals/server-side-apply/

Add: Add sync option (Prod and Dev)

---

manifests/infra/argocd-apps/production/grafana.yaml

Add loki dashboard to prod cluster

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/argocd-apps/production/grafana.yaml

- Sentry, Redis VM に Node Exporter を仕込んだのでそれ用の Dashboard を追加しました

[Prod/Dev] Add node exporter dashboard for sentry

---

manifests/infra/argocd-apps/production/grafana.yaml

- PROD環境にDashboardを追加
- 前回のカンファレンスのDashboardをコメントアウト

Add: Add dashboard "CNDT2023 Dashboard" to PROD

---

dashboards/sentry-overview.json
manifests/infra/argocd-apps/development/grafana.yaml

Add sentry overview dashboard

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-dk/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/development/template-dk/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml

Update: Update DSN

---

dashboards/sentry-overview.json

Redis VMのTail logパネルは、composeのプロジェクト名変更に伴い、self-hosted-sentryのTail  logにマージされたのでパネルを削除しました

Update sentry monitoring dashboard

---

manifests/infra/argocd-apps/production/grafana.yaml

Add sentry monitoring dashboard to prod

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/grafana/overlays/development/externalsecret.yaml

- GrafanaのData SourceにBigQueryを追加
- 手動で入力していた認証をExternalSecretに変更

Add: Add bigquery data source for dev

---

manifests/infra/grafana/overlays/development/externalsecret.yaml

- PEMの扱い方に問題があったため、Base64からデコードできる方法に変更

Fix: Fix external-secret

---

manifests/infra/argocd-apps/production/grafana.yaml
manifests/infra/grafana/overlays/production/externalsecret.yaml

- GrafanaのData SourceにBigQueryを追加
- 手動で入力していた認証をExternalSecretに変更

Add: Add bigquery data source for prod

---

dashboards/cnd-deep-dive.json
dashboards/dk-deep-dive.json
manifests/infra/argocd-apps/development/grafana.yaml

- GA4のデータソースから作成していたダッシュボードをBigQueryのものに変更
- その他軽微の修正
- ロールを`CNDT2023`に変更
- 使用していない不要なプラグインを削除

Feature/add-ga4-bashboard on DEV

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/argocd-apps/production/grafana.yaml

- 本カンファレンス以前のダッシュボードを削除（見返すことがないため）
- 使用しないプラグインを削除
- GrafanaのロールをCNDT2023に変更 (Prod)

Fix: delete dashboards and plugins

---

dashboards/sentry-overview.json

各ダッシュボードのリンク先に含まれていたタイムレンジを抜きました

update dashboard links

---

dashboards/sentry-overview.json

Fixed invalid link of redis dashboard

---

manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml

API Gateway廃止の対応が漏れてました。修正しました

fix: dk-ui reviewapps API_BASE_URL

---

manifests/infra/argocd-apps/production/grafana.yaml

- ProductionのGA Dashboardを修正
- DatasourceをGAからBigQueryに変更

Fix: Fix GA dashboard on production

---

manifests/infra/argocd-apps/production/aws-cluster-autoscaler.yaml

chore(deps): update helm release cluster-autoscaler to v9.32.0

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/argocd-apps/production/grafana.yaml

Update Helm release grafana to v7

---

manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/grafana/overlays/development/externalsecret.yaml

- Sakuraクラウド上に新しく構築したPrometheusをDataSourceとするように設定を変更しました
- Prometheusには、Basic認証の設定が加えられているので、それを解決するための設定項目もいくつか追加しています

[Dev] Update settings for Sakura Prometheus

---

manifests/infra/argocd-apps/production/grafana.yaml
manifests/infra/grafana/overlays/production/externalsecret.yaml

- Sakuraクラウド上に新しく構築したPrometheusをDataSourceとするように設定を変更しました
- Prometheusには、Basic認証の設定が加えられているので、それを解決するための設定項目もいくつか追加しています

[Prd] Update settings for Sakura Prometheus

---

dashboards/sentry-overview-dev.json
dashboards/sentry-overview-prod.json

- Sentry Monitoring DashboardでSentry NodeのNode Exporterのメトリクスが参照できなかったのを直しました
- Devのダッシュボードは、Redisダッシュボードへのリンク先も誤っていたので合わせて修正しています

Fixed sentry monitoring overview dashboard

---

manifests/app/dreamkast/overlays/production/main/cronjob-check_media_live_channel.yaml

fix cronjob name

---

manifests/app/dreamkast/overlays/development/template-dk/mysql.yaml

adjust collation-server parameter

---

manifests/infra/mysql-o11y/overlays/development/cronjob.yaml
manifests/infra/mysql-o11y/overlays/development/secret.yaml

Observability用MySQLへのDumpが失敗していたため、修正しました。
RDSのホスト名が変更されていたことと、過去のRDS(MySQL)用のSecretManagerを参照していたことが原因でした

Fixed invalid reference

---

dashboards/cnds2024-cfp.json
manifests/infra/argocd-apps/development/grafana.yaml
manifests/infra/telegraf/overlays/development/kustomization.yaml
manifests/infra/telegraf/overlays/development/patch-telegraf-deployment.yaml

Telegraf の `CONF_ID` にパッチ当てているものは本番環境のダッシュボードを追加するときに、base側に変更加える予定です

[Dev] Add cnds2024 proposal dashboard

---

manifests/infra/argocd-apps/production/grafana.yaml

Fixed cnds2024-cfp dashboard

---

manifests/infra/prometheus/base/monitor.yaml
manifests/infra/prometheus/overlays/development/service-monitor-dk.yaml

- kube-state-metrics monitorをbaseではなくパッチとして入れてしまっていたので修正

move kube-state-metrics monitor to kustomize base

---

ecspresso/base/common.libsonnet
ecspresso/reviewapps/dk-2267/const.libsonnet
ecspresso/reviewapps/dk-2267/dreamkast-fifo-worker/service-def.jsonnet
ecspresso/reviewapps/dk-2267/dreamkast/service-def.jsonnet
ecspresso/reviewapps/dk-2267/mysql/service-def.jsonnet
ecspresso/reviewapps/dk-2267/redis/service-def.jsonnet
ecspresso/reviewapps/template-dk/const.libsonnet
ecspresso/reviewapps/template-dk/dreamkast-fifo-worker/service-def.jsonnet
ecspresso/reviewapps/template-dk/dreamkast/service-def.jsonnet
ecspresso/reviewapps/template-dk/mysql/service-def.jsonnet
ecspresso/reviewapps/template-dk/redis/service-def.jsonnet
ecspresso/reviewapps/template-ui/const.libsonnet
ecspresso/reviewapps/template-ui/dreamkast-ui/service-def.jsonnet
ecspresso/reviewapps/template-weaver/const.libsonnet
ecspresso/reviewapps/template-weaver/dreamkast-weaver/service-def.jsonnet
ecspresso/reviewapps/template-weaver/mysql/service-def.jsonnet
ecspresso/reviewapps/ui-491/const.libsonnet
ecspresso/reviewapps/ui-491/dreamkast-ui/service-def.jsonnet
ecspresso/reviewapps/weaver-92/const.libsonnet
ecspresso/reviewapps/weaver-92/dreamkast-weaver/service-def.jsonnet
ecspresso/reviewapps/weaver-92/mysql/service-def.jsonnet
ecspresso/stg/const.libsonnet
ecspresso/stg/dreamkast-fifo-worker/service-def.jsonnet
ecspresso/stg/dreamkast-ui/service-def.jsonnet
ecspresso/stg/dreamkast-weaver/service-def.jsonnet
ecspresso/stg/dreamkast/service-def.jsonnet
ecspresso/stg/redis/service-def.jsonnet

assign publicIP to all ECS tasks instead of using VPC Endpoints

---

dashboards/cnds2024-main.json
manifests/infra/argocd-apps/production/grafana.yaml

- CNDS2024ダッシュボードを本番用Grafanaに追加
- 併せて、CNDT2023のダッシュボードを削除

Add: Add CNDS2024 dashboards

---

manifests/infra/argocd-apps/production/grafana.yaml

Fix role attribute path in Auth0 configuration

---

.github/workflows/ecspresso-preview.yml

add github action

---

ecspresso/base/dreamkast.libsonnet
ecspresso/stg/dreamkast/task-def.jsonnet

update template to support empty loki endpoint & mackerel secret

---

ecspresso/base/dreamkast.libsonnet

Review app needs `REVIEW_APP` environment to identify review app.

Add REVIEW_APP environment variable

---

ecspresso/base/dreamkast-weaver.libsonnet
ecspresso/base/dreamkast.libsonnet
ecspresso/reviewapps/template-weaver/dreamkast-weaver/task-def.jsonnet
ecspresso/stg/dreamkast-weaver/task-def.jsonnet

fix some taskDefs

---

ecspresso/prod/const.libsonnet

fix subnet IDs

---

ecspresso/prod/post-registration/ecschedule.yml

fix scheduledTask target role

---

ecspresso/base/dreamkast-weaver.libsonnet
ecspresso/base/dreamkast.libsonnet

adjust QoS for containers

---

manifests/app/seaman/deployment.yaml

stop seaman

---

.github/workflows/autoscale.yml

Description
Follow up PR of #3583

chore: Update replicas environment to prod

---

ecspresso/stg/harvestjob/ecschedule.yml
ecspresso/stg/harvestjob/ecspresso.taskdef.yml
ecspresso/stg/harvestjob/task-def.jsonnet

add harvestjob scheduled task in stg

---

ecspresso/prod/harvestjob/ecschedule.yml
ecspresso/prod/harvestjob/task-def.jsonnet
ecspresso/prod/medialive-alert/ecschedule.yml
ecspresso/prod/post-registration/ecschedule.yml
ecspresso/prod/post-registration/task-def.jsonnet
ecspresso/stg/harvestjob/ecschedule.yml

fix: scheduled tasks for production

---

ecspresso/prod/post-registration/task-def.jsonnet

fix: command

---

ecspresso/reviewapps/template-dk/harvestjob/ecschedule.yml
ecspresso/reviewapps/template-dk/harvestjob/ecspresso.taskdef.yml
ecspresso/reviewapps/template-dk/harvestjob/task-def.jsonnet

chore: enable harvest job on reviewapp

---

ecspresso/base/dreamkast.libsonnet

fix: NAMESPACE value for reviewapp

---

ecspresso/base/dreamkast.libsonnet

Reverts cloudnativedaysjp/dreamkast-infra#3960

Revert "fix: NAMESPACE value for reviewapp"

---

ecspresso/reviewapps/template-dk/initialize.sh

fix: replace variable in each ecschedule.yml

---

ecspresso/base/dreamkast.libsonnet

chore: add printnode api key env

---

ecspresso/base/dreamkast-fifo-worker.libsonnet
ecspresso/base/dreamkast-ui.libsonnet
ecspresso/base/dreamkast-weaver.libsonnet
ecspresso/base/dreamkast.libsonnet
ecspresso/base/mysql.libsonnet
ecspresso/base/redis.libsonnet

add restartPolicy (enabled: true)

---

ecspresso/base/dreamkast.libsonnet

DREAMKAST_NAMESPACEの値の置換条件を変更
- https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1732500418607149

fix: Change the substitution condition for the value of DREAMKAST_NAMESPACE

---

ecspresso/base/dreamkast-fifo-worker.libsonnet

change chrome path

---

.github/workflows/warm-up.yml
ecspresso/prod/harvestjob/vars/disabled.json

stop scale in

---

.github/workflows/warm-up.yml

chore: add debug log

---

.github/workflows/warm-up.yml

fix: enable scale down

---

ecspresso/prod/const.libsonnet
ecspresso/prod/harvestjob/task-def.jsonnet
ecspresso/stg/const.libsonnet
ecspresso/stg/harvestjob/task-def.jsonnet

- Sentryの再構築を行った都合上、DSNが再払い出しとなったためそれに伴う修正です

Update Sentry DSN (prod)

---

ecspresso/reviewapps/dk-2491/initialize.sh
ecspresso/reviewapps/template-dk/initialize.sh

fix: error

---

ecspresso/reviewapps/dk-2489/cleanup.sh
ecspresso/reviewapps/dk-2491/cleanup.sh
ecspresso/reviewapps/template-dk/initialize.sh

https://github.com/cloudnativedaysjp/dreamkast/actions/runs/13568398194/job/37928371941#step:6:278

fix: InvalidParameterException

---

.github/workflows/warm-up.yml

fix warm-up action

---

ecspresso/prod/const.libsonnet
ecspresso/prod/harvestjob/task-def.jsonnet
ecspresso/stg/const.libsonnet
ecspresso/stg/harvestjob/task-def.jsonnet

- Sentryをクラウド版に移行するため、DSNをクラウド版のSentryのものに修正しました

Update Sentry DSN (prod & stg)

---

.github/ghalint.yml
.github/pinact.yml
.github/workflows/ecspresso-format.yml
.github/workflows/ecspresso-preview.yml
.github/workflows/ecspresso.yml
.github/workflows/lint-actions.yml
.github/workflows/warm-up.yml

ref. https://www.notion.so/pfem/Securing-GitHub-Actions-1bb21b0141e080358138e0d9eb65a268

migrate to use reusable-workflows

---

.github/workflows/ecspresso-preview.yml

fix permissions

---

ecspresso/base/const.libsonnet
ecspresso/reviewapps/template-ui/initialize.sh

update event name to cnds2025

---

.github/workflows/ecspresso-preview.yml
ecspresso/stg/harvestjob/task-def.jsonnet

fix: Unknown variable: task

---

.github/workflows/warm-up.yml

debug: stage will be scaled-up

---

.github/workflows/warm-up.yml

debug: stage will be scaled-down

---

ecspresso/base/const.libsonnet
ecspresso/base/dreamkast.libsonnet
ecspresso/base/util.libsonnet
ecspresso/prod/dreamkast/files/otelcol-config.yaml
ecspresso/prod/dreamkast/task-def.jsonnet
ecspresso/stg/dreamkast/files/otelcol-config.yaml
ecspresso/stg/dreamkast/task-def.jsonnet

OpenTelemetry collectorをdreamkastのsidecarとして起動する。

OpenTelemetry collectorをdreamkastのsidecarとして起動する

---

ecspresso/base/const.libsonnet
ecspresso/base/dreamkast.libsonnet
ecspresso/base/util.libsonnet
ecspresso/prod/dreamkast/task-def.jsonnet
ecspresso/stg/dreamkast/task-def.jsonnet

OpenTelemetry collectorのみにしよう。

mackerel-container-agentを外す

---

ecspresso/prod/dreamkast/task-def.jsonnet

prod用のDocker image `607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-otelcol:branch-main` はpushしてある
[generate-code · cloudnativedaysjp/dreamkast-otelcol@5dd9477](https://github.com/cloudnativedaysjp/dreamkast-otelcol/actions/runs/17767059437/job/50493011459)
Secret ManagerでMackerelのAPIキーも設定した。

prodのdreamkastタスクにもOTel collectorを設定する

---

ecspresso/base/dreamkast.libsonnet
ecspresso/stg/dreamkast/files/otelcol-config.yaml

送信元のRailsの設定は https://github.com/cloudnativedaysjp/dreamkast/pull/2577 となる。
送られるtraceの様子 : https://cloudnativedays.slack.com/archives/C02MAP9EHAA/p1758219358193209
以下のvalidateコマンドは通る。
```sh
docker run -v 云々/dreamkast-infra/ecspresso/stg/dreamkast/files:/mnt 607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/dreamkast-otelcol:branch-main validate --config otelcol-config.yaml
```

stg環境のdreamkastタスクでtraceをMackerelに送信できるよう設定する
