argocd-infra/argocd-apps.yaml

タイトル通り
ディレクトリ構成は後段の PR で以下のように整える予定 (他案があればください！)
```
.
├── cfn
│   └── <現状の /cnf 以下のファイル群>
└── manifests
├── app
│   ├── argocd-apps
│   │   └── <現状の /argocd-apps 以下のファイル群>
│   ├── dreamkast
│   │   └── <現状の /dreamkast 以下のファイル群>
│   └── dreamkast-api-mock
│       └── <現状の /dreamkast-api-mock 以下のファイル群>
├── argocd
│   └── <現状の /argocd 以下のファイル群>
└── infra
├── argocd-apps
│   └── <現状の /argocd-infra 以下のファイル群>
└── contour
   └── <現状の /contour 以下のファイル群>
```

external-secrets を ArgoCD App にて Helm を用いてデプロイするようにした

---

manifests/app/argocd-apps/development/dreamkast-dk-459.yaml
manifests/app/argocd-apps/development/dreamkast-dk-509.yaml
manifests/app/argocd-apps/development/dreamkast-staging.yaml
manifests/app/argocd-apps/development/dreamkast-ui-46.yaml
manifests/app/argocd-apps/development/dreamkast-ui-49.yaml
manifests/app/argocd-apps/development/dreamkast-ui-51.yaml
manifests/app/argocd-apps/development/dreamkast-ui-52.yaml
manifests/app/argocd-apps/production/dreamkast-main.yaml
manifests/app/argocd-apps/template/dreamkast.yaml

- (念の為) staging が dev / prd のどちらのクラスタに居ても良い用に ArgoCD Application の命名を変更
- この PR は以下の PR の前提となっています
- cloudnativedaysjp/dreamkast#511
- cloudnativedaysjp/dreamkast-ui#53
- 当 PR の merge 時、一度すべての dreamkast が Argo CD により cascade delete されるため注意 (まだユーザに晒してないので横着してこのまま行かせてください:pray:)

update ArgoCD Apps' name

---

manifests/app/dreamkast/base/pdb.yaml

dreamkast-ui podのappラベル、dreamkastだったのでこの部分は不要でした

Remove dreamkast-ui

---

manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/redis.yaml

以下より普段の CPU / Memory 使用量を確認してそれっぽい値を resources.limits と redis.conf に記述
https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=ElasticCache;start=P14D

[staging] Redis 移行: ElastiCache > K8s Deployment

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/production/main/redis.yaml
manifests/app/dreamkast/overlays/staging/main/redis.yaml
manifests/app/dreamkast/overlays/template/redis.yaml

#50 の production 版
こちらも以下を参考にそれっぽい値を利用 (本当は負荷テストをやる必要があると思いますが、dreamkast はセッションストアでしか redis を利用していないことを確認したため、取り敢えずこれだけあれば十二分に足りると思っています)
* https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=ElasticCache;start=2021-02-25T15:00:00Z;end=2021-02-26T14:59:59Z
* pre event の日にち
* https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=ElasticCache;start=P14D
* ここ二週間

[production] Redis 移行: ElastiCache > K8s Deployment

---

manifests/app/argocd-apps/development/dreamkast-releasebot.yaml
manifests/app/dreamkast-releasebot/base/deployment.yaml
manifests/app/dreamkast-releasebot/base/ingress.yaml
manifests/app/dreamkast-releasebot/base/kustomization.yaml
manifests/app/dreamkast-releasebot/base/secret.yaml
manifests/app/dreamkast-releasebot/base/service.yaml
manifests/app/dreamkast-releasebot/overlays/development/kustomization.yaml

https://github.com/cloudnativedaysjp/dreamkast-releasebot を dev で動作させるための PR
- GITHUB_TOKEN
- SLACK_BOT_TOKEN
- SLACK_VERIFICATION_TOKEN

dreamkast-releasebot 用マニフェストの配置

---

manifests/app/dreamkast/base/deployment.yaml

from cloudnativedaysjp/modify-base-dreamkast"
This reverts commit 63b83438bff377d8cf4c9aa27ea440be201e44b3, reversing
changes made to 611b63e9c0701fb8bd6c0077784d347b36efe90c.

Revert "Merge pull request #269 

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

merge 後 Argo CD にて sync error が発生するので以下の対応をする
* エラーの理由: dreamkast Deployment の matchLabel が immutable Field であるため
* 対応: dreamkast Deployment を kubectl から削除し、その後すぐ Argo CD WebUI よりデプロイを実施する

update dreamkast's base manifests

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

This reverts commit 511c0f81af71c3c980bda244d2a470ad7553688f, reversing
changes made to d471758a44c560edcf2459773a47ba992a6054cf.
https://github.com/cloudnativedaysjp/dreamkast/pull/621 でboothがunpublishedにならなくなるので戻します

Revert "Merge pull request #297 from cloudnativedaysjp/disable_db_seed"

---

manifests/argocd/overlays/production/argocd-apps/dreamkast.yaml
manifests/argocd/overlays/production/argocd-apps/metrics-server.yaml

dev cluster廃止に伴いマニフェストの当て先をprd clusterに変更

---

manifests/infra/contour/base/contour.yaml

backend protocolを削除してIPモードのNLBを使う

---

cfn/sqs.yaml
manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

メール送信用にSQSに `MailQueue` を作成  
パラメータは FIFO queue であること以外は基本 default を使用しています
ActiveJob の Worker 用にプロセスを作る必要があるのですが、これをどのノードにまかせるべきかが未定なので検討後パラメータに追加する必要があります(Draft でとどめています)

メール配信用に SQS のリソースを追加

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml
manifests/app/dreamkast/overlays/production/main/secret.yaml

- 毎朝10時にcndt2021チャンネルにCICD2021の登録者人数を通知します。
fix https://github.com/cloudnativedaysjp/dreamkast/issues/710

add cronjob to notify registration situation to slack

---

manifests/argocd/overlays/development/argocd-apps/loki.yaml
manifests/argocd/overlays/production/argocd-apps/loki.yaml

```
$ k -n monitoring get all -l release=loki
NAME                      READY   STATUS    RESTARTS   AGE
pod/loki-0                1/1     Running   0          19m
pod/loki-promtail-ggmxq   1/1     Running   0          19m
pod/loki-promtail-xlfdd   1/1     Running   0          19m
pod/loki-promtail-z2ht2   1/1     Running   0          19m
NAME                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/loki            ClusterIP   10.96.220.71   <none>        3100/TCP   19m
service/loki-headless   ClusterIP   None           <none>        3100/TCP   19m
NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/loki-promtail   3         3         3       3            3           <none>          19m
NAME …
```

add loki, promtail via loki-stack

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml
manifests/app/dreamkast/overlays/template/ingress.yaml

CICDでUIを有効にするための修正。
本当はワイルドカードを使ってどのパスであっても対応できるようにしたかったけど、Contourはそれが出来ない様子・・・
https://github.com/projectcontour/contour/issues/1179
CNDOのパスはもう使うことがないので削除。今のままだとCNDT2021でも同様の対処は必要になるが、
https://github.com/cloudnativedaysjp/dreamkast/issues/674
が実現できればそもそもこのroutesは不要になるため、今回はCICD向けのハードコードで対処することにした。くそダサいので今回限りにしたい･･･

Change route for UI

---

manifests/argocd/overlays/development/argocd-apps/cert-manager.yaml
manifests/argocd/overlays/development/argocd-apps/external-secrets.yaml
manifests/argocd/overlays/production/argocd-apps/cert-manager.yaml
manifests/argocd/overlays/production/argocd-apps/external-secrets.yaml

現行のバージョンだとCRDのバージョンが古くて1.23に壊れてしまうため、そうなる前に上げておく

Upgrade cert manager and external secrets

---

manifests/app/argocd-apps/production/dreamkast-releasebot.yaml

* fix #795
* dev cluster だけじゃなく prd cluster からも dreamkast-releasebot を消してしまったので、 prd にのみデプロイし直し

prd cluster に dreamkast-releasebot をデプロイ

---

cfn/sqs.yaml

連続で同じメッセージを入れた場合に無効化されるので、少なくとも開発環境では不要と判断しました。

SQSの設定からコンテンツに基づく重複排除設定を無効にする

---

manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml

https://github.com/cloudnativedaysjp/dreamkast/pull/858 で環境変数の設定ミスによってキューイングに失敗している問題を修正
manifest 内で誤って initContainer だけに環境変数を設定していたため、定義を追加しました。

Job キューイングに失敗していた問題を修正

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml

```
~ $ k logs post-left-idea-issues-to-slack-27210300-9rtdp
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
config.eager_load is set to nil. Please update your …
```

need RAILS_ENV

---

manifests/app/dreamkast/overlays/staging/main/kustomization.yaml

kustomization に mail-worker が記述されておらず不十分な状態で動作しており、Podが上手く作成できない不具合を解消

staging の kustomization に mail-worker を追加

---

manifests/argocd-apps/dev/grafana.yaml

https://grafana.com/blog/2021/10/05/grafana-7.5.11-and-8.1.6-released-with-critical-security-fix/

dev: update grafana from 8.1.5 to 8.1.6

---

manifests/argocd-apps/prd/grafana.yaml

https://grafana.com/blog/2021/10/05/grafana-7.5.11-and-8.1.6-released-with-critical-security-fix/
ref dev: update grafana from 8.1.5 to 8.1.6 #973
https://grafana.dev.cloudnativedays.jp/ 見た感じ、大丈夫そうですが、気になることがありましたらお知らせください。

prd: update grafana from 8.1.5 to 8.1.6

---

manifests/argocd-apps/dev/grafana.yaml

ref #426 
https://grafana.dev.cloudnativedays.jp/ に作成した"Kubernetes Pod created via UI"ダッシュボードのJSONを追加しました。
ダッシュボードの内容がこれでよいかは、"Kubernetes Pod created via UI"を見てください。
マニフェストがこれでよいかは `kubectl apply -f manifests/argocd-apps/dev/grafana.yaml` するとよいのでしょうが、argocdのsyncで元に戻ってしまいます。どうするのがよいでしょうか？
* `manifests/argocd-apps/dev/grafana.yaml`と`manifests/argocd-apps/prd/grafana.yaml`両方にJSONをべたーっと書くのか、シュッとまとめられるのか。
* Memory utilization per Podの凡例にPod名のみ表示したい。

dev: create Kubernetes Pod dashboard

---

manifests/argocd-apps/dev/grafana.yaml

自作ダッシュボード名に半角スペースは使えませんでした。
> ConfigMap "grafana-dashboards-default" is invalid: data[Kubernetes Pod.json]: Invalid value: "Kubernetes Pod.json": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name', or 'KEY_NAME', or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

dev: fix a invalid value of grafana-dashboards-default

---

manifests/infra/contour/overlays/development/contour.yaml

[CVE-2021-32783](https://github.com/advisories/GHSA-5ph6-qq5x-7jwc)への対応とかパフォーマンスfixが含まれる
マイナーバージョンなのでサクッと上げてしまう
1.19が出てるけど変更箇所が大きいのでCNDT後にする

Update contour to 1.18.2

---

cfn/eks-nodes.yaml

DreamkastからMediaLive Channelを作るためにはインスタンスプロファイルにPassRoleが必要なので追加します。

allow PassRole

---

manifests/argocd-apps/dev/grafana.yaml

Helm Chartのアップデートもあるが、脆弱性対応としてはイメージのアップデートのみ行う。
https://grafana.com/blog/2021/11/03/grafana-8.2.3-released-with-medium-severity-security-fix-cve-2021-41174-grafana-xss/

dev: bump grafana from 8.1.6 to 8.2.3 to fix CVE-2021-41174

---

manifests/argocd-apps/prd/grafana.yaml

prd: bump grafana from 8.1.6 to 8.2.3 to fix CVE-2021-41174

---

manifests/app/dreamkast/overlays/template/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/template/deployment-mail-worker.yaml

sqs の stack を更新した際に以前のキュー名の変更が適用されてしまい review_app でうまく起動しなくなっていたので修正
* old では `devQueue` だったが current では `dreamkast-devQueue` が正になっている
* cfn が更新されていたが、スタックは更新されていなかったため顕在化しなかった
* chat キューを作るためにスタックを更新したので prefix の変更が環境にも適用された
* stg/prod では prefix が入っているため影響していない

fix sqs queue name

---

manifests/reviewapps/dreamkast.yaml

ref: #1165
Reviewapp operatorへの移行が過渡期なのもあって、こちらのほうにも入れないとDkのReview appに反映されないです

Add DREAMKAST_NAMESPACE env into reviewapp

---

manifests/argocd-apps/dev/jaeger.yaml

https://github.com/helm/charts/issues/13077 によると
> If you install jaeger chart with name jaeger, environment variable JAEGER_AGENT_PORT will be automatically created by Kubernetes (as string) and jaeger-client-go expects integer (just the port number, not url) under the same name so it is going to fail. The easiest way to fix the problem would be to install jaeger under some different name
ということなので、chartの名前を変えて再度デプロイします

modify jaeger chart name

---

manifests/argocd-apps/dev/aws-ebs-csi-driver.yaml

ref #1243
dev-clusterの設定
```shell
helm get values aws-ebs-csi-driver -n kube-system
```
```yaml
USER-SUPPLIED VALUES:
controller:
region: ap-northeast-1
serviceAccount:
create: false
name: ebs-csi-controller-sa
```

dev: manage aws-ebs-csi-driver by argocd

---

manifests/infra/prometheus/base/prometheus.yaml

現在のリソースステータス
```
(base) ry@mbp2020 Desktop % k get pods,pvc                                                       
NAME                                            READY   STATUS    RESTARTS   AGE
pod/elasticsearch-master-0                      1/1     Running   0          34h
pod/elasticsearch-master-1                      1/1     Running   0          34h
pod/elasticsearch-master-2                      1/1     Running   0          34h
pod/grafana-0                                   1/1     Running   0          35h
pod/jaeger-tracing-agent-29rfq                  1/1     Running   0          34h
pod/jaeger-tracing-agent-hm767                  1/1     Running   0          34h
pod/jaeger-tracing-agent-htnkq                  1/1     Running   0          34h
pod/jaeger-tracing-agent-jhxb9 …
```

Make prometheus volume persistent

---

manifests/argocd-apps/dev/prometheus.yaml

Dev環境におけるArgoCDのsyncがmanualでの実施となっているため、Auto-syncに変更するための修正を実施。
This PR is to change Argo's syncPolicy from manual to auto-sync on developing environment.
PrometheusのManifestに一時的な変更を加えるために、ArgoCDのsyncPolicyをmanualに修正していた。
Due to fixing #1253, I've temporarily turned syncPolicy into manual.

Changed argo' syncPolicy from manual  to auto-sync

---

manifests/infra/prometheus/overlays/development/kustomization.yaml
manifests/infra/prometheus/overlays/development/service-monitor.yaml

PrometheusのFilesystem使用率に関して現状の最大値を把握するため、モニタリングの定義を追加。
#1253 #1252 #1265

Prometheus monitor

---

manifests/argocd-apps/dev/grafana.yaml

Grafana in development environment will be updated to fix CVE-2021-43798, path traversal.
https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
8.2.7 would be better?
ref #1277

dev: bump grafana from 8.2.3 to 8.3.1 to fix CVE-2021-43798

---

manifests/argocd-apps/dev/cluster-autoscaler.yaml

install cluster-autoscaler on dev cluster.
ref #1243
cluster-autoscaler is running.
The resource names managed by helm are different from the current resource names.
We'll have to delete the current resources before/after merging this PR.
1. comment out `syncPolicy`
2. `kubectl apply -f manifests/argocd-apps/dev/cluster-autoscaler.yaml`
3. manually sync via Argo CD UI

dev: manage cluster-autoscaler by argocd

---

manifests/app/dreamkast/overlays/staging/main/delete-deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

Fix the problem that enqueueing mail and other jobs fails in staging environment due to the effect of renaming workers and changing queues.
#1208 
- I have `kubectl -n dreamkast-staging diff -f manifests/app/dreamkast/overlays/staging/main/delete-deployment-mail-worker.yaml` and `kubectl -n dreamkast-staging diff -f manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml` to make sure there are no errors.

Modify the staging worker name

---

manifests/app/dreamkast/overlays/production/main/cronjob.yaml
manifests/app/dreamkast/overlays/production/main/deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/production/main/viewer-count.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/staging/main/viewer-count.yaml
manifests/reviewapps/dreamkast-ui.yaml
manifests/reviewapps/dreamkast.yaml

`dreamkast-dev` is a default Jaeger service name that dreamkast sets if `DREAMKAST_NAMESPACE` is not specified.
We did not properly set this value for mail worker and batch jobs, and this PR covers it. 
Production Grafana currently recognizes those jobs as `dreamkast-dev`
Locally applied, but this won't break anything as it just adds environment variable.

Add namespace env on side jobs

---

manifests/app/dreamkast/overlays/production/main/delete-deployment-mail-worker.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-fifo-worker.yaml
manifests/app/dreamkast/overlays/production/main/kustomization.yaml

Fix the problem that enqueueing mail and other jobs fails in production environment due to the effect of renaming workers and changing queues. This change is same to #1287.
#1208
**Note that the timing needs to be synchronized with the release of the application to the production environment.**
- Unproven as there is no production config in my `kubectl`.

prd の mail-worker を fifo-worker に変更

---

manifests/infra/prometheus/overlays/production/kustomization.yaml
manifests/infra/prometheus/overlays/production/prometheus.yaml

Fixes a part of https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1265
```diff
diff -u -N /tmp/LIVE-1252176878/monitoring.coreos.com.v1.Prometheus.monitoring.k8s /tmp/MERGED-3422743700/monitoring.coreos.com.v1.Prometheus.monitoring.k8s
--- /tmp/LIVE-1252176878/monitoring.coreos.com.v1.Prometheus.monitoring.k8s     2021-12-15 22:38:07.966735730 +0900
+++ /tmp/MERGED-3422743700/monitoring.coreos.com.v1.Prometheus.monitoring.k8s   2021-12-15 22:38:07.966735730 +0900
@@ -5,13 +5,12 @@
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/versio …
```

Incraese Volume Size on production Prometheus

---

manifests/infra/telegraf/base/configmap.yaml

expose total proposal count via telegraf like this.
```
dreamkast_proposals_count 4
```
Fixes cloudnativedaysjp/observability#8
I manually deployed `deployment/telegraf-oke-py` and `configmap/telegraf-oke-py`.
I executed `kubectl port-forward telegraf-oke-py-xxxxxxxxxx-xxxxx 9273:9273` and opened `http://localhost:9273/metrics`.

expose total proposal count

---

manifests/infra/telegraf/base/configmap.yaml

expose proposal count by difficulty via telegraf like this.
```
dreamkast_talk_difficulties_count{talk_difficulty="中級者"} 2
dreamkast_talk_difficulties_count{talk_difficulty="初級者"} 2
```
Fixes https://github.com/cloudnativedaysjp/observability/issues/9
I manually deployed deployment/telegraf-oke-py and configmap/telegraf-oke-py.
I executed `kubectl port-forward telegraf-oke-py-xxxxxxxxxx-xxxxx 9273:9273` and opened `http://localhost:9273/metrics`.

expose proposal count by difficulty

---

manifests/infra/telegraf/base/deployment.yaml

Fix cloudnativedaysjp/observability#12
1) add `--watch-config`
2) remove subpath as it will not automatically detect cm changes
Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
> Note: A container using a ConfigMap as a subPath volume will not receive ConfigMap updates.
Tested locallly by changing `debug` flag in config. Verified file reloads occurs.
```
2021-12-21T14:21:45Z I! Config file modified
2021-12-21T14:21:45Z I! Reloading Telegraf config
2021-12-21T14:21:45Z D! [agent] Stopping service inputs
2021-12-21T14:21:45Z D! [agent] Input channel closed
2021-12-21T14:21:45Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-12-21T14:21:45Z D! [outputs.prometheus_client] Wrote batch of 115 metrics in 2.399497ms
2021-12-21T14:21:45Z …
```

Restart telegraf when updated configmap

---

manifests/reviewapps/dreamkast.yaml

Reflect the change in the kubernetes manifest because the command to execute the worker has been changed.
https://github.com/cloudnativedaysjp/dreamkast/pull/1048
Initially, an error will occur due to the non-existence of the queue, but we will create a separate P/R for this issue.
We have confirmed that it works fine when the queue is created.

modify woker command

---

cfn/sqs.yaml

The `delaySeconds` parameter of the SQS queue is set to 10, which interferes with the real-time performance of chat, so fix it to 0.

Modify SQS parameters for low latency chat delivery

---

cfn/eks-nodes-bottlerocket.yaml

https://github.com/cloudnativedaysjp/dreamkast/issues/989 で進めている新しい録画アーキテクチャでは[lAWS MediaPackage](https://aws.amazon.com/jp/mediapackage/)を使うようになる。しかし、NodeInstanceRoleがMediaPackageを扱う権限を持っていないので許可する。
```
dreamkast-774db758dd-qpdkr dreamkast E, [2022-01-16T04:00:17.879864 #13] ERROR -- : [ActiveJob] [CreateMediaPackageJob] [f051b191-ccf6-4b5c-876d-35c2749b0fca] User: arn:aws:sts::607167088920:assumed-role/dreamkast-dev-eks-nodes-bottleroc-NodeInstanceRole-5Q272N37VA19/i-0d58afeeafdf8a311 is not authorized to perform: mediapackage:TagResource on resource: arn:aws:mediapackage:us-east-1:607167088920:channels/*
```

アーカイブ録画機能実装のため、NodeInstanceRoleがMediaPackageにアクセスできるようにします

---

cfn/eks-nodes-bottlerocket.yaml

https://github.com/cloudnativedaysjp/dreamkast/issues/989 で進めている新しい録画アーキテクチャでは[lAWS MediaPackage](https://aws.amazon.com/jp/mediapackage/)を使うようになる。しかし、MediaLiveからMediaPackageを利用する際にSSMのパラメータストアを使わなければならないが、権限がなかった。PutParameterとDeleteParameterがあればよいので許可する。
```
dreamkast-774db758dd-qpdkr dreamkast E, [2022-01-16T04:00:17.879864 #13] ERROR -- : [ActiveJob] [CreateMediaPackageJob] [f051b191-ccf6-4b5c-876d-35c2749b0fca] User: arn:aws:sts::607167088920:assumed-role/dreamkast-dev-eks-nodes-bottleroc-NodeInstanceRole-5Q272N37VA19/i-0d58afeeafdf8a311 is not authorized to perform: mediapackage:TagResource on resource: arn:aws:mediapackage:us-east-1:607167088920:channels/*
```

medialiveからmediapackageを扱うにあたり、ssmのパラメータストアにアクセスする必要があるので許可する

---

cfn/eks-nodes-bottlerocket.yaml

https://github.com/cloudnativedaysjp/dreamkast/issues/989 で進めている新しい録画アーキテクチャでは[lAWS MediaPackage](https://aws.amazon.com/jp/mediapackage/)を使うようになる。https://github.com/cloudnativedaysjp/dreamkast-infra/pull/1367 でPutParameterとDeleteParameterを扱うポリシーを追加したのだが、Resourceの指定方法が間違っていたので修正する。
```
dreamkast-774db758dd-qpdkr dreamkast E, [2022-01-18T09:57:36.510645 #13] ERROR -- : [ActiveJob] [CreateMediaLiveJob] [9d6575b7-cae7-4d53-96c0-76b3d9d23ede] User: arn:aws:sts::607167088920:assumed-role/dreamkast-dev-eks-nodes-bottleroc-NodeInstanceRole-5Q272N37VA19/i-0d58afeeafdf8a311 is not authorized to perform: ssm:PutParameter on resource: arn:aws:ssm:us-east-1:607167088920:parameter/medialive/review_app_1096_cndt2021_trackB because no identity-based policy allows the ssm:PutParameter action
```

Resourceでregionとaccount idを指定する必要があった

---

manifests/argocd-apps/prd/grafana.yaml

Fixes https://github.com/cloudnativedaysjp/observability/issues/19
「DBをわけるのがダッシュボード公開条件」の「公開範囲」に
- 実行委員の他チームが含まれる => #1299 および後続タスクを待つ
- 一般参加者のみが含まれる => https://github.com/cloudnativedaysjp/dreamkast-infra/issues/1279 未完了のためマージしてよい
https://grafana.dev.cloudnativedays.jp/d/N4HUPtT6z/o11y2022-proposal is working.

prd: add #o11y2022 proposal dashboard

---

manifests/argocd-apps/prd/metrics-server.yaml

Update metrics-server to 0.5.2
https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.0 basically contains performance and reliability improvements, the base version is now 1.21 that matches the EKS cluster veresion.

update metrics server to 0.5.2

---

manifests/infra/mysql-o11y/base/cronjob.yaml
manifests/infra/mysql-o11y/base/deployment.yaml
manifests/infra/mysql-o11y/base/kustomization.yaml
manifests/infra/mysql-o11y/base/pv.yaml
manifests/infra/mysql-o11y/base/pvc.yaml
manifests/infra/mysql-o11y/base/service.yaml
manifests/infra/mysql-o11y/overlays/development/cronjob.yaml
manifests/infra/mysql-o11y/overlays/development/secret.yaml
manifests/infra/mysql-o11y/overlays/production/cronjob.yaml
manifests/infra/mysql-o11y/overlays/production/secret.yaml

Baseレベルのnamespace指定は不要です。
Baseレベルでnamespaceを指定されると、手元の環境でNamespaceの変更が難しくなりますので、直させてください。
`kustomize build` してもnamespaceがちゃんと付与されることを確認しています。

Remove uneeded namespace at base level

---

manifests/app/dreamkast/overlays/production/main/polling-harvest-job-and-update-video.yaml
manifests/app/dreamkast/overlays/staging/main/polling-harvest-job-and-update-video.yaml
manifests/reviewapps/dreamkast.yaml

This PR adds cronjob to run `rake util:polling_harvest_job_and_update_video` command that is added by https://github.com/cloudnativedaysjp/dreamkast/pull/1100 . This Cronjob polling Harvest Job of AWS Media Package.
https://github.com/cloudnativedaysjp/dreamkast/issues/989

add cronjob for rake task polling-harvest-job-and-update-video

---

manifests/argocd-apps/dev/grafana.yaml

ダッシュボードの削除を有効化

---

dashboards/Contour-HTTProxy.json
dashboards/Kubernetes-Pod.json
dashboards/o11y2022-cfp.json
dashboards/o11y2022-main.json

uidが競合しているのが問題のため、ダッシュボードのjson内のuidを空にして適用することで、既存のダッシュボードと競合しないようにする。
uidはJSON内で任意に採番もできるが、一旦指定なしにすることでランダムなuidを振り直す
ランダムなuidを振り直した時の影響として、下記のようなDashboardのURLが変わるということ点があるが現状どこからもリンクされていないので影響なしと判断
```
https://grafana.dev.cloudnativedays.jp/d/MAc3Yf-nk/o11y2022dashboard?orgId=1
```
ref #1536

Grafana Dashboardの明示的なuid指定を削除

---

dashboards/o11y2022-main.json

Dreamkastから取得する、参加者登録数、チャット数、視聴者数メトリクスの最新値を表示するダッシュボードの作成
Related to
- https://github.com/cloudnativedaysjp/observability/issues/17
- https://github.com/cloudnativedaysjp/observability/issues/21

参加者登録数、チャット数、視聴者数の最新値を表示

---

manifests/argocd-apps/dev/jaeger.yaml
manifests/argocd-apps/prd/jaeger.yaml

Jaegerがまともに動いてないので（おもにElasticsearchのせい）、All in Oneでインメモリストアする構成にする。永続性はまあそんなに重要じゃないと思っているが必要であれば検討する形にする。どのみち動いてないので本番もいっしょにあげちゃう
ref. https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger#all-in-one-in-memory-configuration

remove elasticsearch from jaeger

---

dashboards/o11y2022-main.json

o11y2022に向けたダッシュボードの修正
- チャット数ダッシュボードの数値が赤くなる件
- time rangeを「現在から30日前」、から、「現在から1日前」に変更
- プレイベントダッシュボードの削除
- いいね数ダッシュボードの値取れてない問題の対処
- 感情分析ダッシュボードの重複排除
- 各パネル(Dreamkast, Twitter)の説明書きの追加

本番に向けたダッシュボードの修正

---

manifests/infra/prometheus/overlays/development/kube-state-metrics/kustomization.yaml

Fixes #1619 
kube-state-metrics が monitoring Namespace に居なかったので、Prometheus のスクレイピング対象におらず、アラートも効いていませんでした。

change target namespace of kube-state-metrics: kube-system > monitoring

---

manifests/infra/prometheus/overlays/development/kube-state-metrics/alert-rules.yaml

* Fixes #1641
* in current, alert rule is not matched at all :cry: 🙇 
* this PR make alert-rule become sensitive. if it's so noisy, I will improve it.

fix alert that reviewapp-operator Pod become crash

---

manifests/argocd-apps/dev/falco.yaml

Reverts cloudnativedaysjp/dreamkast-infra#1709
Bottlerocket OS上ではeBPF moduleのDLに失敗して最小権限モードで動かなかった

Revert "Add Helm options to Falco chart"

---

manifests/argocd/overlays/dev/argocd-cm.yaml

On the known issue, `kustomize-with-replacements` ArgoCD Plugin does not work well when we write applicationset.yml for ReviewApp as below (unrelated lines are snipped).
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
name: example
spec:
template:
spec:
source:
plugin:
name: kustomize-with-replacements
env:
- name: IMAGES
value: >-
dreamkast-ecs=public.ecr.aws/q5p7z1m4/dreamkast-ecs:{{head_sha}},
dreamkast-ui=public.ecr.aws/q5p7z1m4/dreamkast-ui:main
```
In the last 3 lines, I use `>-` literal, which replaces "new line (`\n`)"  with "space (` `)".
But I was misunderstood as `>-` replaces "new line (`\n`)"  with "no character (``)". So `kustomize-with-replacements` Argo CD Plugin does not work well.
I fixed this issue in this PR.
---
* No Issue
* reference on Slack: …

NO-ISSUE: on ArgoCD Plugin: fix bug occurred when a space contains in input

---

manifests/app/chatbot/configmap.yaml

remove the following targets because CODT2022 has been finished.
* https://github.com/cloudopsdays/dreamkast_codt2022
* https://github.com/cloudopsdays/dreamkast-ui_codt2022
add the following target 
* https://github.com/cloudnativedaysjp/chatbot/

update targets on chatbot

---

manifests/app/dreamkast/overlays/development/template-dk/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/production/main/deployment-dreamkast.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast.yaml

`db:seed_fu` getting failed because seed_fu doesn't read a helper file. To resolve this, I changed init command to use `db:seed`

Use db:seed instead of seed_fu

---

manifests/argocd-apps/prd/grafana.yaml

GrafanaのGithub dashboardが、devだとデータ保持期間が短すぎてIssue数の推移が見れないので、prodにdeployさせてください。
privateに配置して非公開なので、prodにおいて問題ない認識です（そもそもIssue数は公開情報なので、公開しても良いかもですが）

Add Github Dashboard to prod

---

manifests/app/dreamkast/overlays/staging/main/hpa.yaml
manifests/argocd-apps/dev/keda.yaml
manifests/infra/keda-external-scalers/overlays/development/dreamkast-external-scaler.yaml
manifests/infra/keda-external-scalers/overlays/development/kustomization.yaml

No Issue
* Install [KEDA](https://github.com/kedacore/keda) & [dreamkast-external-scaler](https://github.com/cloudnativedaysjp/dreamkast-external-scaler)
* apply KEDA ScaledObject to dreamkast-staging
* KEDA ScaledObject:
* threshold 1: CPU 50% (as usual)
* threshold 2: minReplicas is adjusted to ScaledObject.spec.triggers.metadata.minReplicas if today is conference date
* remove HPA

Install KEDA & Install to dreamkast-staging

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/development/template-dk/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

CICD2023のプレイベント向けの動作確認をしようと思ったら、マニフェスト側がCNDT2022のまま更新されておらずアクセスできなかったので、修正しました。

Replace cndt2022 hardcoded with cicd2023

---

manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/base/service.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-weaver.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/kustomization.yaml

- [dreamkast-weaver](https://github.com/cloudnativedaysjp/dreamkast-weaver)のmanifestをstagingに追加
- dk/dk-uiと同じnamespaceに作成
- 追加したリソース
- Service
- dk/dk-uiはNodePortが設定されてましたが、設定理由がよく分からなかったのでClusterIPに変更しています。
- port番号はキメです
- HTTPProxy
- fqdnは一旦`tmp.dev.cloudnativedays.jp`としています
- `api.dev.cloudnativedays.jp`とするべきなのですが、dk-function側でまだ利用しているので、一時的なドメインで実装をすすめ、別途切り替える予定です
- Deployment
- Prove周りは既存のdeploymentを参考に設定しています
- 確認したこと
- 下記コマンドでdevデプロイできることを確認
```bash
kustomize build manifests/app/dreamkast/overlays/staging/main/ | kubectl apply -l tier=dreamkast-weaver -f -
```
- `https://tmp.dev.cloudnativedays.jp/`に接続できることを確認

feat: Add dreamkast-weaver in staging

---

cfn/eks-nodes-bottlerocket.yaml

Remove m3.xlarge from the list of nodegroup because it doesn't support client ip preservation.
https://docs.aws.amazon.com/ja_jp/elasticloadbalancing/latest/network/load-balancer-target-groups.html#client-ip-preservation

Remove m3.xlarge

---

manifests/app/dreamkast/overlays/development/template-dk/kustomization.yaml
manifests/app/dreamkast/overlays/staging/main/redis.yaml

Change redis image tag from 6.0.5 to 6.0.
Because Amazon ECR public registry doesn't have 6.0.5 tag.
https://gallery.ecr.aws/docker/library/redis

Change tag from 6.0.5 to 6.0

---

manifests/infra/contour/overlays/production/kustomization.yaml

PRDのcontourで`kustomize build`に失敗していたので修正しました。
- 修正前
```
$ kustomize build overlays/production/ | head
Error: accumulating resources: accumulation err='merging resources from 'https://projectcontour.io/quickstart/v1.24.1/contour.yaml': may not add resource with an already registered id: Namespace.v1.[noGrp]/projectcontour.[noNs]': failed to run '/usr/bin/git fetch --depth=1 https://projectcontour.io/quickstart/v1.24.1 HEAD': fatal: repository 'https://projectcontour.io/quickstart/v1.24.1/' not found
: exit status 128
```
- 修正後
```
$ kustomize build overlays/production/ | head
apiVersion: v1
kind: Namespace
metadata:
name: projectcontour
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
annotations:
controller-gen.kubebuilder.io/version: v0.11.2
```

fix: rollback to 7da9927

---

manifests/infra/prometheus/base/kustomization.yaml
manifests/infra/prometheus/overlays/development/kustomization.yaml
manifests/infra/prometheus/overlays/production/kustomization.yaml

- `kustmoize build`に失敗していたので修正しました
- alert-rules.yamlが無くて死んでいた
- `xxx must resolve to a file: recursed accumulation of path`と言われ死んでいた
- ぱっとみ、https://github.com/cloudnativedaysjp/dreamkast-infra/pull/2574 と同じに見えた
- 修正前
<details>
```
fujii@ubuntu:/data/ghq/github.com/cloudnativedaysjp/dreamkast-infra/manifests/infra/prometheus$ kustomize build overlays/production/ | head
Error: accumulating resources: accumulation err='accumulating resources from '../../base': '/data/ghq/github.com/cloudnativedaysjp/dreamkast-infra/manifests/infra/prometheus/base' must resolve to a file': recursed accumulation of path '/data/ghq/github.com/cloudnativedaysjp/dreamkast-infra/manifests/infra/prometheus/base': accumulating resources: accumulation err='accumulating resources from 'alert-rules.yaml': evalsymlink …
```

fix: prometheus

---

manifests/application-dev.yaml

#2581 にて manifests/application-production.yaml のみ syncOptions.prune: false に変更したため、dev でも同様の設定を実施

update prune option

---

manifests/infra/mysql-o11y/base/deployment.yaml

mysql-o11yが再起動の都度dataが削除されてしまい、次のdaily batchが来るまでdataが空のまま -> telegrafが死んでしまう、という事象をさけるために、PVCをmountしてmysql dataを永続化します。
PVC mountするだけなのと運用ツールなので、devで確認してからprodと細かくstep踏まなくてもいいかなと思い、baseの方を更新してしまってます。devとprodの両方に適用されます。

fix: Persist mysql-o11y data to avoid data loss when restarted

---

manifests/app/dreamkast/overlays/staging/main/ingress.yaml
manifests/infra/argocd-apps/development/contour.yaml
manifests/infra/contour/base/kustomization.yaml
manifests/infra/contour/base/namespace.yaml

* support Pod readiness gates for rollout without down
* https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/deploy/pod_readiness_gate/
* revert these PRs
* #2629
* #2621

Support Pod readiness gates

---

manifests/app/dreamkast/overlays/production/main/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/staging/main/deployment-dreamkast-ui.yaml

dk-ui -> dkの通信で、api-gatewayを経由しないようにしました（すでに削除されているので）
バグってて動かない状態になっているので、復旧優先でmergeしちゃいます。

fix/dk-ui: Call dk directly without via proxy

---

manifests/infra/prometheus/overlays/development/service-monitor-dk.yaml

Reverts cloudnativedaysjp/dreamkast-infra#2887
テスト完了したためrevertします

Revert "update service-monitor"

---

ecspresso/base/const.libsonnet
ecspresso/reviewapps/template-ui/initialize.sh
ecspresso/reviewapps/ui-499/initialize.sh
manifests/app/dreamkast/base/deployment.yaml
manifests/app/dreamkast/overlays/development/template-dk/ingress.yaml
manifests/app/dreamkast/overlays/development/template-ui/deployment-dreamkast-ui.yaml
manifests/app/dreamkast/overlays/development/template-ui/ingress.yaml
manifests/app/dreamkast/overlays/production/main/ingress.yaml
manifests/app/dreamkast/overlays/staging/main/ingress.yaml

cndt2023に向いていたものを全てcnds2024にかえました。
ecspressoの方はよくわかってないのですが、cndt2023である必要はないと思い変えています。

feat: Switch cndt2023 to cnds2024

---

ecspresso/base/dreamkast.libsonnet
ecspresso/stg/const.libsonnet
ecspresso/stg/dreamkast/task-def.jsonnet

```
$ jsonnet ./ecspresso/stg/dreamkast/task-def.jsonnet
```
<details>
<summary>task-def.json</summary>
```json
{
"containerDefinitions": [
{
"command": [
"bundle exec rails db:migrate; bundle exec rails db:seed;"
],
"cpu": 64,
"dependsOn": [
{
"condition": "HEALTHY",
"containerName": "log_router"
}
],
"entryPoint": [
"/bin/bash",
"-c"
],
"environment": [
{
"name": "RAILS_ENV",
"value": "production"
},
{
"name": "MYSQL_HOST",
"value": "dreamkast-stg-rds.cctlaulyxvbk.us-west-2.rds.amazonaws.com"
},
{
"name": "MYSQL_DATABASE",
"value": "dreamkast"
},
{
"name": "REDIS_URL",
"value": "redis://redis.staging.local"
},
{
"name": "SENTRY_DSN",
"value": "TODO"
},
{
"name": "S3_BUCKET",
"value": "dreamkast-stg-bucket"
},
{
"name": "S3_REGION",
"value": "us-west-2"
},
{
"name": …
```

Add log router and mackerel agent for dreamakast staging

---

ecspresso/stg/harvestjob/ecschedule.yml
ecspresso/stg/harvestjob/task-def.jsonnet

fix harvestjob

---

ecspresso/prod/harvestjob/task-def.jsonnet
ecspresso/prod/medialive-alert/task-def.jsonnet
ecspresso/prod/post-registration/task-def.jsonnet
ecspresso/prod/seaman/task-def.jsonnet

fix roleName & specify region as variable

---

ecspresso/reviewapps/dk-2484/cleanup.sh
ecspresso/reviewapps/dk-2486/cleanup.sh
ecspresso/reviewapps/dk-2487/cleanup.sh
ecspresso/reviewapps/dk-2489/cleanup.sh
ecspresso/reviewapps/template-dk/initialize.sh

- DKのReviewApp環境が残る問題の対処を入れました
- see: https://www.notion.so/pfem/2025-02-23-1a321b0141e080ad8425fcb490cee847?pvs=4#1a321b0141e0808ab100d467f5777792
- 事象
- DKのReviewApp環境ではTargetが設定されたEventBridgeが作成される
- https://us-west-2.console.aws.amazon.com/events/home?region=us-west-2#/eventbus/default/rules/dk-2490-harvestjob
- [creanup script](https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/ecspresso/reviewapps/dk-2489/cleanup.sh#L7)でEventBridgeの削除を試みているが、Targetが付与されているため、削除できないエラーが発生
- https://github.com/cloudnativedaysjp/dreamkast/actions/runs/13453103343/job/37591157532
- その結果、ReviewApp環境のコード削除にたどり着くことなく終了し、環境が残り続ける
- 対処
- Targeを削除する一文を書いた
- creanup.shはinitialize.shで生成しているので、そちらにも一文書いた

DKのReviewApp環境が残る問題の対処

---

ecspresso/base/dreamkast.libsonnet
ecspresso/prod/dreamkast/task-def.jsonnet
ecspresso/stg/dreamkast/task-def.jsonnet

現在、新しくECSタスクが起動した時、それがホストとしてMackerelに登録されるが、ロールはホスト毎に手動で設定する必要がある。mackerel-container-agentに環境変数を設定する事で、ホストが自動でロールに登録されるようになる。
https://mackerel.io/ja/docs/entry/howto/container-agent#:~:text=mackerelio.com/)%E3%80%82-,MACKEREL_ROLES,-%E3%82%BF%E3%82%B9%E3%82%AF%E3%80%81Pod%E3%81%B8
下記botの出した環境の差分を見た。環境変数が追加されるのはOK。DISABLEDが色々と空文字になるのはわからない…。

新しく起動したタスクをMackerelのロールに自動で登録する

---

.github/workflows/warm-up.yml

* push commits by GitHubApp instead of using workflow-trigger
* because deploy action triggered by workflow-trigger pull old commits sometimes.

update warm-up action

---

ecspresso/base/dreamkast.libsonnet

Fixes # None
stgのdreamkastが以下のようなエラーを吐きタスクの起動に失敗し続けている。
```
CannotPullContainerError: pull image manifest has been retried 1 time(s): failed to resolve ref [607167088920.dkr.ecr.us-west-2.amazonaws.com/dreamkast-otelcol:main-7e3e1f8805628b477b671f9a960b3cf989d0bf10](http://607167088920.dkr.ecr.us-west-2.amazonaws.com/dreamkast-otelcol:main-7e3e1f8805628b477b671f9a960b3cf989d0bf10): [607167088920.dkr.ecr.us-west-2.amazonaws.com/dreamkast-otelcol:main-7e3e1f8805628b477b671f9a960b3cf989d0bf10](http://607167088920.dkr.ecr.us-west-2.amazonaws.com/dreamkast-otelcol:main-7e3e1f8805628b477b671f9a960b3cf989d0bf10): not found
```
このタグのコンテナイメージがECRに無いからである。上記の `main-7e3e1f8805628b477b671f9a960b3cf989d0bf10` はdreamkast-ecsコンテナのイメージタグであり、間違っている。dreamkast-otelcolコンテナのイメージタグを指定せねばならない。 …

dreamkast-otelcolコンテナは最新のtagを参照する

---

ecspresso/prod/dreamkast/files/otelcol-config.yaml
ecspresso/stg/dreamkast/files/otelcol-config.yaml

dreamkastサービスのotelcolコンテナがexit 1で落ちている。
再現させる : 
```console
% OTELCOL_CONFIG="$(cat ~/dev/cloudnativedays/dreamkast-infra/ecspresso/stg/dreamkast/files/otelcol-config.yaml)" docker compose up
[+] Running 1/1
✔ Container dreamkast-otelcol-otelcol-dreamkast-1  Recreated                                                                                                                                                                                    0.0s 
Attaching to otelcol-dreamkast-1
otelcol-dreamkast-1  | Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
otelcol-dreamkast-1  | 
otelcol-dreamkast-1  | 'receivers' the logging exporter has been deprecated, use the debug exporter instead
otelcol-dreamkast-1  | …
```

the logging exporter has been deprecated, use the debug exporter instead
